### ISSUE TITLE
Fixes of activity rules for import

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1082]
**Tasks**
- [x] Recipient country percentage rules
- [x] Transaction sector, recipient region and recipient country rules
- [x] Rules in sector, recipient region and recipient country
- [x]  Update rules that are currently using params id for import

**Comment by sriza** [comment]
Merged to main branch and closed manually.
