### ISSUE TITLE
Activity import using XLS

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1101]
**Tasks**
- [x] Breakdown activity elements based on complexity and build a sample XLS file
- [x] Research regarding multi-sheet xls
- [x] Create a template /mapping structure for XLS to JSON mapping of activities
- [x] Reading data present in XLS
- [x] Validation of activity
- [x] Store in valid.json file
- [x] Storing and updating in database
- [x] Result, indicator and period code creation and download
- [x] Script to fill unique code on result, indicator and period that already exists
- [x] Import UI 
- [x] Api for UI

**Comment by sarinasindurakar** [comment]
- [ ] The Activity Date type can be multiple so changed the color into blue.
- [ ] Activity status: color changed into white cause it is 1..1 element.
- [ ]

**Comment by sarinasindurakar** [comment]
- [ ] Remove the participating organization reference dropdown from the xls.
-

**Comment by sarinasindurakar** [comment]
- [ ] The cancel import button is not redirecting the user out of the import page.It only shows the toast message.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/38d82e19-65e4-4b41-9a92-0647b97b72e5)

**Comment by sarinasindurakar** [comment]
- [ ]  When user  leaves the activity identifier field empty and tries to import the file, the process does not stops .It keeps on showing the progress  pop up of uploading the file  but file is not imported.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/98e88ddd-c3d9-4285-9e6e-162bd60743c4)

- [ ] When user adds the '0' in the activity identifier field , the process does not stops .It keeps on showing the progress  pop up of uploading the file  but file is not imported.
- [ ] When user enters only language and activity identifier in the title sheet, "Untitled" not shown. It also doesnot shows "Untitled" when user adds only activity identifier in the title sheet.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/8cecac03-17c1-4ad3-9942-953fd566e231)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/ad87f0c3-d4bd-48ba-8d4e-349616cc7b85)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/91290f34-6b7f-405b-a538-c2f2cf4c9741)

- [ ] Two option of 638 and 639 is missing from the dropdown of the default finance type.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/272ab9c0-3717-40ce-bd83-f948c039f3df)

- [ ] When user does not fill the activity identifier and adds data on other field in the "Element with single field", it is shown as new activity without any data.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/909869c0-8d3d-4a09-9d8f-983d76c899ca)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/07ca1a52-3ac2-4ad9-9781-3029c57385a7)

**Comment by sarinasindurakar** [comment]
- [ ]  when user uploads the other template xls file  by selecting the other option ,the wrong warning message is shown.
The warning message should be "The header doesnot match".

https://github.com/younginnovations/iatipublisher/assets/65848732/12fc8e60-5a30-44df-a4fe-dafb70505ff8

**Comment by sarinasindurakar** [comment]
- [ ] When user adds the invalid language in title->language, no warning message is shown.No default  value was taken.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/2b306c25-f4a8-4603-920d-fffc617fe273)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/914a2c75-bcb0-476a-bbbf-d95313e304b5)

**Comment by sarinasindurakar** [comment]
- [ ] The condition's attached multiple case warning message not shown for first activity in xls.
- [ ] The result xls file not uploaded.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/1639e36d-1cce-45a9-ab98-0f8eef956c07)

**Comment by sarinasindurakar** [comment]
- [ ] The same error message is shown multiple times with same sheet name  and row number.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/13d1d2dc-817e-4f27-bfbc-7866fe66bcce)

**Comment by sarinasindurakar** [comment]
- [ ]  when user tries to import the same activity while import is processing, the activity is title is shown untitled even when title is provided. 

https://github.com/younginnovations/iatipublisher/assets/65848732/08eb015c-6be0-4cf6-8e28-0452c428fb66

- [ ] When user cancels the import between the processing, and tries to import  other file then following incomplete  error message is is shown.

https://github.com/younginnovations/iatipublisher/assets/65848732/bb6c328f-1fe6-4f8a-b656-b4e137f32c32

- [ ] The  import error popup retry button is not working.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/7f5e25ed-e818-40f9-8a96-99ff3b88b2b1)

- [ ]

**Comment by sarinasindurakar** [comment]
- [ ] Make Changes in  Download code information in the import page according to design. Here I have added new design.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/ce00e1a8-a330-47cf-a757-10583daa45a1)

- [ ] When user tries to import upload the file,the following error is shown.

https://github.com/younginnovations/iatipublisher/assets/65848732/279e7747-c21c-4616-a591-e7ee732ff776

**Comment by sarinasindurakar** [comment]
- [ ]   Replace the filename according to the user uploads the file like "Basic Activity Elements", "Result Except Indicator" etc. Also replace with this " Import Anyway".
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/2ebc76bb-675a-4f1d-b496-90aaddf74634)

**Comment by sarinasindurakar** [comment]
- [ ]   When user uploads the large  file then, the count of the progress bar is showing the wrong .

**Comment by sriza** [comment]
Merged to main branch and closed manually.
