### ISSUE TITLE
Fill Default Values on save

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1107]
Currently, the default values are filled on the activity and organization elements on save. But sometimes these values fail to be filled. This issue is related to finding out specific conditions on which it fails and fixing them

**Tasks**
- [x] Fill default value in activities (create and update)
- [x] Fill default values in organization (create and update)
- [x] Fill default values during import of activity (new and existing)
