### ISSUE TITLE
Setting, Signup and Signin Feedbacks

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#112]
**Tasks**

- [x] Reset password link doesn't work.-
- [x] When the credentials don't match, highlight the password field box too.
- [x] In Publisher Information, the '*' is missing in Publisher ID field
- [x] Update the country list including the country code as per the list here - https://docs.google.com/spreadsheets/d/1okv1yB6iIU0Uzf-qGxpphNhF8xctsMTYLPWdmOtryDE/edit#gid=1964476832
- [x] Update the Organisation Registration Agency list including the code as per the list here - https://docs.google.com/spreadsheets/d/1okv1yB6iIU0Uzf-qGxpphNhF8xctsMTYLPWdmOtryDE/edit#gid=150070354 and make sure the list is shown based on the country selected along with common agencies.
- [x] In verification email use the following content,
> Dear {Full name},
> Welcome to IATI Publisher. Your email has been used to create a new account here. Please click the button below to verify that you have created the account in it.
> Button 
> Regards,
> IATI Publisher 
- [x] In Administrator Information, highlight the 'Confirmation Password' text box when the passwords don't match.
- [x] In Administrator Information, show the field is required for confirmation password if it is not filled.
- [x] Mention '* Mandatory fields' above the form in both forms
- [x] Check if 'Publisher Name', 'Publisher ID', 'IATI Organisation Identifier' already exist in the system, if any of them exist, restrict them to go ahead. Reason: There should not be more than one account which can publish for same organisation.
- [x] Remove '* Mandatory fields' and remove '*' and validation while saving
- [x] Replace the placeholders with 'Type Publisher ID here' for Publisher ID and 'Type API Token here' for API Token
- [x] Make Publisher ID uneditable and no need to show 'correct' or 'incorrect'
- [x] Don't save the API token when 'Verify' is clicked
- [x] Check if the Default Hierarchy is 1, 2 or 3 and show error if the value is not empty, 1, 2 or 3. If empty save it as 1 in database.
- [x] Change the list of currency to the list found in this document: https://docs.google.com/spreadsheets/d/1AYj0Nn6StKUu2S23BIYa8o7OadWr_uJkFtuvWOtU5WU/edit#gid=1821171131

**Design Task**
- [x] Design has the navbar content and signin form aligned
- [x] On hover, nav links color doesn’t change
- [x] Dropdown opens on hover
- [x] Next button padding
- [x] Help text/ error msg has 4px extra top padding
- [x] Line hight of error message
- [x] “IATI Registry” and “support@iatistandard.org” are linked as primary color
- [ ] Username field is supposed to be auto generated
- [x] Register page sidebar

**Comment by praweshsth** [comment]
**Sign up**
- [ ] In publisher information, after everything is filled up, check if 'Publisher ID' match with IATI registry, if it doesn't then just show 'Publisher ID' doesn't exist in IATI Registry

**Settings - Publishing Settings **
- [ ] Don't show 'The api token field is required' when it is empty and user try to verify or save it. Just show the incorrect status.

**Comment by andreaszenasidi** [comment]
@praweshsth Few issues were found during functionality testing.

**1. **Contact Support** link doesn’t work**
**URL:** https://stage.iatipublisher.yipl.com.np/ 
**Issue:** Contact Support button doesn’t do anything just reloads the page.

**2. Join Now ->I am new to IATI**
**URL:** https://stage.iatipublisher.yipl.com.np/
**Issue:** Doesn’t work,  takes you back to the home page.

**3. Error message needs a space after Publisher Name.** 
**URL:** https://stage.iatipublisher.yipl.com.np/register 
 **Issue:** This text needs to be replaced “Please note that if you’re an account holder in [IATI Registry](https://iatiregistry.org/), make sure your Publisher Name,Publisher ID and IATI Organisation ID match your IATI Registry Information. Contact [support@iatistandard.org](mailto:support@iatistandard.org) for more details.” Use this text instead: “Please note that if you’re an account holder in IATI Registry, make sure your Publisher Name, Publisher ID and IATI Organisation ID match your IATI Registry Information. Contact [support@iatistandard.org](mailto:support@iatistandard.org) for more details.”
![image](https://user-images.githubusercontent.com/74558657/167865973-6df2f18b-8527-4849-aa46-a71bf452a1f4.png)

**4. Right side Steps panel Title layout is misaligned in Firefox v 100.0**
**URL:** https://stage.iatipublisher.yipl.com.np/register 
 **Issue:** Right side Steps panel Title layout is misaligned in Firefox v 100.0.  Applies to only Step 1 and Step 2 titles.
![image](https://user-images.githubusercontent.com/74558657/167866003-f305f054-18ca-49fe-9424-3ebb168d020e.png)
![image](https://user-images.githubusercontent.com/74558657/167866033-e97a1794-650a-467c-9503-4e64291b68fb.png)

**5. Remove extra space in successful account creation content**
 **Issue:** Remove extra space in successful account creation content. Replace “A verification email has been sent to andreas@devinit.org .” WITH “A verification email has been sent to andreas@devinit.org.”
![image](https://user-images.githubusercontent.com/74558657/167866074-3ff5def9-30a3-4b89-b00c-04d92aec17b6.png)

**6. After successful account creation I do not receive an email**
**Issue:** Join Now -> My organization has an account -> Sign up. At the end I receive the successfully created account message and to verify my account but I didnt receive confirmation email that my account was created. I checked my spam folder as well. 

**7. When I try to reset my password I do not receive the email to my email [andreas@devinit.org](mailto:andreas@devinit.org)**

**8. The API Token generation help page is an incorrect link at the moment**
![image](https://user-images.githubusercontent.com/74558657/167866236-dfc9fbbe-2bb4-4634-ae6d-5035d015e35e.png)

**9. Incorrect menu item highlighted**
**Issue:** When I am in the Settings menu the menu item Settings is not underscored with the light blue colour, it's still the Activity Data menu item that is underscored.
![image](https://user-images.githubusercontent.com/74558657/167866595-abb6523b-2f38-4403-81c8-02c6e69fb1e7.png)

**Comment by praweshsth** [comment]
Thank you @andreaszenasidi for the feedback. Below are our response to your feedback:

1. we will add the email link to IATI Support 
2. since we will be developing the sign up for not registered in IATI registry later only, for now, we will freeze the block so nothing will happen. But if you have any suggestions other than that, do provide us the suggestion.
3. We will replace the text as per your suggestions. However, we might have to work together on different messages and alerts later on. We are currently working on the design of such messages. Lets list down the possible messages that system will display to the user and we can implement them. 
4. We will check the system in firefox and fix the issue and we will also check the system in other browsers such as Microsoft Edge, Safari
5. We will make the changes
6. We are using Gmail SMTP and for us it was working fine. And we looked in our sent messages, it was in the sent messages. Please use another email to test it. And if the problem persists then we will use another SMTP. 
7. Same as no. 6
8. As per the feedback in the content of the setting page for this, we will remove the text below the API token field. In hover over text has the information on how to get the API token. 
9. We will fix it.

**Comment by andreaszenasidi** [comment]
@praweshsth new issue found.

When I use again a publisher (e.g. Development Initiatives Poverty Research) from the IATI registry that I already signed up in the IATI Publisher, after I enter the information on the screen and click Next Steps nothing happens, no error message is shown. 

![image](https://user-images.githubusercontent.com/74558657/168254520-58299d5e-8f82-45cb-a88b-ce6dcc75426b.png)

**Comment by praweshsth** [comment]
@andreaszenasidi I checked with the same information, it took me to next step to enter the admin information. Please check it once again. If the problem persists then we will look into it. Yesterday, we had added another changes. May be you want to do a hard refresh.

**Comment by andreaszenasidi** [comment]
@praweshsth the issue is that in Firefox v 100.0 the Next Step button doesn't do anything just refreshes the page, but doesn't even trigger the validation because if I leave all the cells empty no error message is displayed.
https://stage.iatipublisher.yipl.com.np/register

**Comment by praweshsth** [comment]
@Man0zZ please check the sign up flow in Firefox v 100.0 and resolve the issue mentioned by @andreaszenasidi

**Comment by praweshsth** [comment]
@andreaszenasidi both the issues you have mentioned has been resolved. @Man0zZ tested in Firefox v100.0 and found that it was working. And @sriza has worked on the issue but hasn't updated in the staging. She will do it tomorrow.

**Comment by praweshsth** [comment]
@sriza 

1. In the footer, please change the IATI Standard part as per the [document](https://docs.google.com/document/d/16G0tjT1iprHO2jIp3cn9cyFC1HGnt8FUl5zWXaoWldo/edit#heading=h.xqnus0flgxbv)
2. In Sign up page's description part, change 'Haven't registered yet? Sign in' to 'Already have an account? Sign in'
3. In reset password, when the password don't match, highlight both fields
4. In Default setting, use the list of language from this list - https://docs.google.com/spreadsheets/d/1okv1yB6iIU0Uzf-qGxpphNhF8xctsMTYLPWdmOtryDE/edit#gid=1429184668
5. In Default setting, the option for Humanitarian is already set to 'Yes', Keep it empty like other fields.

**Comment by andreaszenasidi** [comment]
@praweshsth Thanks for making the changes. The email looks good now. But the form still doesn't behave as expected in Firefox. I can show you in today's catchup call if that helps.

**Comment by man-git007** [comment]
@sriza @praweshsth @SauravSilwal10 Can we close this issue?
