### ISSUE TITLE
Update Env credentials

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#1131]
Update credentials present in the `.env` file of stage, production, and development

**Tasks**
- [x] mail credentials [No need]
- MAIL_USERNAME
- MAIL_PASSWORD
- [x] AWS credentials
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- [ ] IATI validator
- IATI_VALIDATOR_KEY
- IATI_API_KEY
- IATI_USERNAME
- IATI_PASSWORD
- IATI_PUBLISHER_API_KEY
- [x] Mix encryption key
- MIX_ENCRYPTION_KEY

**NOTES**
1. Make sure APP_KEY which was exposed was of the local machine
2. For what `MIX_ENCRYPTION_KEY` is used and update that credentials as well
3. As  the minio service is not used. Close the service in the minio server 

@A4family Look into this and update the credential and coordinate with @pravinbanjade. This needs to be resolved as soon as possible by the first hour today @sriza and @pravinbanjade

**Comment by man-git007** [comment]
@sriza @pravinbanjade @A4family 
No need to update the mail credentials as it was of local system

cc @bikramtuladhar

**Comment by pravin-yipl** [comment]
- [x] Deleted old AWS Access Key and added new access key for user iati-dev
- [x] Deleted user iati_user from minio

**Comment by sriza** [comment]
@man-git007 @pravin-yipl @A4family @bikramtuladhar 
The update of mail credentials, AWS credentials, Mix Encryption Key, and the IATI API key is enough.

Please update the IATI_API_KEY on your local environment as well, since the exposed key will be deleted.

The IATI_PUBLISHER_API_KEY is just for testing purposes, and IATI_USERNAME and IATI_PASSWORD are to authenticate to the staging site alone. It is not necessary to change them.
