### ISSUE TITLE
Environment variable updates

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#1150]
**Tasks**
- [x] Remove seal-secret bash file [Not needed]
- [x] Remove secret yaml file
- [x] Regenerate certificate [Not needed] 
- [x] Add secret and seal secret files to another location
- [x] Make documentation for generating sealed secret
- [x] Separate mix_encryption_key for each server(prod, dev, staging)
- [x] Update credentials of env (DB password, mail password, AWS keys, IATI_VALIDATOR_KEY, MIX_ENCRYPTION_KEY)

cc @praweshsth @Sanilblank @sriza

**Comment by man-git007** [comment]
@pravin-yipl What is the status of this issue? Is it done, if yes let's close this issue.

cc @sriza
