### ISSUE TITLE
XLS download for activity, result, indicator and period

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1171]
**Tasks**
- [x] Users should be able to either download all activities, or select specific activities and download their data
- [x] Upon clicking download button, users will have downloaded 4 files: activity, result, indicator and period which will have template similar to xls upload
- [x] The downloaded xls file should be uploadable to IATI publisher

**Comment by sarinasindurakar** [comment]
- [ ] Hierarchy data not shown in downloaded file.
- [ ] There is no data in dropdown of humanitarian of setting. It is only showing the value 1 in it.
![image](https://user-images.githubusercontent.com/65848732/236784744-9362f713-fe10-4979-b4d6-98ab19b96232.png)
- [ ] In the description, the description type  data is shown invalid data. It is different from the data entered manually.
![image](https://user-images.githubusercontent.com/65848732/236785151-d24bfc6f-66a6-4f78-9047-642adbe48bc0.png)
![image](https://user-images.githubusercontent.com/65848732/236785412-422c30f2-bfb8-441c-a72f-fbd7931a159a.png)
- [ ] The activity date type is showing the different data and the dropdown option of the activity date type is of description type . Change them.
![image](https://user-images.githubusercontent.com/65848732/236785688-599cdf5b-5c2b-4398-9f21-b807aef6d5b5.png)
![image](https://user-images.githubusercontent.com/65848732/236786014-5ba52a1d-3b00-4aab-94d0-61f765d1db9e.png)

- [ ] The free text vocabulary code of the sector and tag not shown in the xls file.
![image](https://user-images.githubusercontent.com/65848732/236787330-e82b5819-03ea-45db-be45-22c3fe1291dd.png)

**Comment by sarinasindurakar** [comment]
- [ ] The "download" button of the email is redirecting to the IATI login page. The file is not being downloaded.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/cdbb519a-f282-48b5-a1c9-87d22d0daf15)

**Comment by A4family** [comment]
- [ ] Indicator.xls (file) => Indicator Document Link (Sheet Name) => Language Code (Column Name) "Language Code columns was blank"
- [ ] Indicator.xls (file) => Baseline Document Link (Sheet Name) => Language Code (Column Name) "Language Code columns was blank"
- [ ] Indicator.xls (file) => Indicator Baseline (Sheet Name) => Comment Language (Column Name) "Comment Language value was incomplete"
- [ ] Period.xls (file) => Target & Period (Sheet Name) => "blank line in between when there are multiple values in its document link "

**Comment by sarinasindurakar** [comment]
- [ ] The secondary reporter false data not shown in file.

**Comment by sarinasindurakar** [comment]
- [ ]  When user downloads the xls file,the result number is shown in +13 format and the result identifier is shown 0.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/726060e9-52a0-45e3-8ab1-94ca77540cf8)

**Comment by sarinasindurakar** [comment]
- [ ]  when user downloads the activity while other download is on process,  the other download is on process popup is shown multiple times.

https://github.com/younginnovations/iatipublisher/assets/65848732/a26c646c-cab0-40f9-b764-106be8eb78bc

- [ ] No cross button in download  process popup.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/3102f115-373c-4199-8b8c-841b38e3aa37)

**Comment by sarinasindurakar** [comment]
- [ ] The support button is overlapping popup.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/307e5990-14f9-4481-81a6-7676e1ccd505)

**Comment by sarinasindurakar** [comment]
- [ ]  When user clicks the cancel button, it is taking time . Reduce the time.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/26b9447c-0f06-48f3-96c9-14832b7eb9b9)

- [ ]   when user navigates to import page while downloading the xls file, bulk publish popup is also shown form no where even when it is not done.

https://github.com/younginnovations/iatipublisher/assets/65848732/f8874906-4ace-4011-b882-d81284cc07d5

**Comment by sarinasindurakar** [comment]
- [ ]  When user downloads the activity, bulk  publish popup is also displayed in it.
- [ ] The download popup is shown only after refreshing the page.
https://github.com/younginnovations/iatipublisher/assets/65848732/a04425dc-568b-4c9c-a8c3-98e4c3ca09fb
- [ ] When user downloads the file , download complete popup is shown even before processing.

Uploading Copy of IATI Publisher Dev - 7 June 2023 (1).mp4…

**Comment by sarinasindurakar** [comment]
- [ ] The download popup  is shown only after refreshing the page after downloading  the activity in computer.

https://github.com/younginnovations/iatipublisher/assets/65848732/924e0bb1-20d5-4c2a-9e1d-612fa2993c01

**Comment by sarinasindurakar** [comment]
- [ ]  When user bulk publish the activity, the  some activities bulk publish fails. The two toast of retry  and successful toast is overlapping.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/64a9cf46-a2df-4bf4-a6f3-896565062012)

- [ ]  When user unpublishes the activity it is stuck in almost there and need to refresh the page.
- [ ] The toast message of bulk publish is not shown.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/53885dc7-4bda-4c2e-b3df-77c90b93e24b)

- [ ]  Don't show the import, download popup message in the unpublish ,publish processing modal.

https://github.com/younginnovations/iatipublisher/assets/65848732/9c583dc8-f7ea-4c19-84a5-c1bba2d7b3b9

**Comment by sarinasindurakar** [comment]
- [ ]  Two cancel button purpose is same.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/f6a7e378-2a93-43de-b756-f369b8094c9e)

**Comment by sriza** [comment]
merged to main branch. Closed manually.
