### ISSUE TITLE
Dashboard with Visualization

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1185]
**Tasks**
- [x] Update database as required for visualization
- [x] Api for visualization
- [x] Visualization UI

**Comment by sarinasindurakar** [comment]
- [ ] The **last updated** date for all migrated and old organizations has been modified to 19 hours ago.
![image](https://user-images.githubusercontent.com/65848732/234763927-a38dca63-ba26-4fad-8fc8-d9b676ce3b4e.png)

- [ ] If the field is empty in contact info, the text "Missing" is not displayed in the migrated organization.
![image](https://user-images.githubusercontent.com/65848732/234764733-3aa10bba-ac66-4071-ae8d-99fbf74dbb22.png)

**Comment by sarinasindurakar** [comment]
- [ ]  The organization page is shown blank
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/d7de8b2d-a530-40c3-b78d-d8382f0b5868)

- [ ] Add some spacing  same as user page in dashboard too.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/4ad00804-0318-4494-8698-2d2bfd9a9b7d)
.

**Comment by sarinasindurakar** [comment]
- [ ] Truncate the publisher name.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/2d9ade19-14e4-4496-a906-848f9987659c)

**Comment by amritlc** [comment]
1. 

- [ ] In /list-organisations page when applying calendar filter and if no data available then calender seems not responsive and crushed up and not showing apply and cancel
![2023-06-26_09-38](https://github.com/younginnovations/iatipublisher/assets/52846176/524d90ba-537c-4bb6-955f-6ef05a4d1573)
 buttons.

**Comment by sarinasindurakar** [comment]
### Users

- [ ] 34  There is no users by organization section in user tab.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/cabee52a-d1c0-4f1a-a23e-7d920b4a69fe)
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/ddd24eff-3461-44b5-bd6c-b300830f77d3)

- [ ] 35 The graph line visualization in shown.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/ba159a80-4db9-4614-894a-7ba4ddcc1e61)

**Comment by sarinasindurakar** [comment]
### Issues after Retesting

- [ ]  The publisher's  count  is incorrect  in all the date range filter.
- [ ]  The count of the publisher's settings not completed  is incorrect.
- [ ] The half data is only being downloaded in the report of publisher, users, activity.
- [ ] The last activity update of  organization name is not updated in the activity.
- [ ]  Users filter from today to this month is not showing any data in the graph.

**Comment by sarinasindurakar** [comment]
- [ ] 1 When user clicks over the date filter, the calendar should be shown below the date filter.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/fadf802a-f6ad-4944-b926-e88b1f3f2191)

- [ ]  2 Remove the white space in the user count table.

![image](https://github.com/younginnovations/iatipublisher/assets/65848732/efa54379-2aa2-4147-9043-5d1bfc215793)

- [ ] 3 Generals user filter  from user dashboard to organization list is not working properly.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/a907ce49-739e-4c69-bd10-18c44dbf9ed2)

- [ ] 4 Displaying the organization specific user in the user list is not working properly.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/c6bcd1be-faf2-4d08-9224-477f504c9138)

- [ ] 5 The filter option is also shown empty in the user page.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/8e97e1b9-5fce-4de9-86c0-0522d8c5d114)

- [ ] 6 Add scrollbar in the publisher type dropdown.
- [ ]  7 In the case of setup completeness, registration type filter  of organization page, close the dropdown once user selects the it's option .
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/199d1e62-ac10-4e6c-ba45-64263bba3788)

- [ ]  Make the filter of the organization page dropdown  open when user  click where ever  within the box.

- [ ] Add the close icon (cross)  on the publisher type  button too after selecting the option.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/dff3dd95-665a-42c3-ac2f-67b1ecd6cceb)
-

**Comment by sarinasindurakar** [comment]
- [ ] Only  half of the data is shown in publisher type and country. It may be due to pagination as the pagination is not shown.

https://github.com/younginnovations/iatipublisher/assets/65848732/a1426075-2602-4225-9dad-b86563a8b34b

**Comment by sarinasindurakar** [comment]
- [ ]  Show the total number of organizations in the organization listing page.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/8b86705a-4af3-49cf-8efb-9973f0060fec)

- [ ] The organization listing page should be filtered according to organization registered date. But in our system,  it is being filtered according to the user registered date.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/8020d282-4e7b-4322-a9e3-66f47888a4e4)

- [ ] Add the total number of users and  date filter option in the users page too.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/1a53770f-bdae-43d9-b299-ce4ce15569ce)

**Comment by sarinasindurakar** [comment]
- [ ]  Show the total number of organizations in the organization listing page.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/8b86705a-4af3-49cf-8efb-9973f0060fec)

- [ ] The organization listing page should be filtered according to organization registered date. But in our system,  it is being filtered according to the user registered date.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/8020d282-4e7b-4322-a9e3-66f47888a4e4)

- [ ] Add the total number of users and  date filter option in the users page too.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/1a53770f-bdae-43d9-b299-ce4ce15569ce)

- [ ] When user selects the  this year filter, 6 month data is shown in the filter in all the cases.

https://github.com/younginnovations/iatipublisher/assets/65848732/6eccf199-de92-4662-8f1b-3a16e0b38e7b


- [ ] When user downloads the data of the publisher, the  publisher settings and default values  doesn't matches with the total count. The more count of complete default value and publisher setting is shown.
Date: 6 months 
Total data: 85
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/e38219c4-9489-4ff8-aabe-772ae42c35c7)
File:
[publisher-report (16).csv](https://github.com/younginnovations/iatipublisher/files/11975029/publisher-report.16.csv)


- [ ] The sorting option of the user is not working properly. If the data is sorted in page 1,then other data is not sorted in  other pages. Need to send order by from frontend.

https://github.com/younginnovations/iatipublisher/assets/65848732/40966988-a02d-47fa-ad16-c81acf5d512e



- [ ] If the user is in User Listing Page and goes to page number 2 , the it's pagination is also being carried to the publisher page too. The pagination index is shown "1" but page no 2's data is being displayed in publisher type.

https://github.com/younginnovations/iatipublisher/assets/65848732/9476240f-4f3c-40d4-8bae-6f267b363917

**Comment by sarinasindurakar** [comment]
- [ ]  1 If the user sorts the data even after going back and forth, the data must be sorted.

- [ ] 2 The count of the total activities in all the data is different.

![image](https://github.com/younginnovations/iatipublisher/assets/65848732/5b163f80-2877-49cf-b563-a3930763afc0)

**Comment by sarinasindurakar** [comment]
- [ ] All time tag not shown in publisher.

![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/50c1778e-1f0f-4f14-85eb-681c81906f82)

- [ ] The user  by organization section data should not change according to date filter.
- [ ]  WHen user clicks on the organization in the user page , the date should not be taken in the user page.
- [ ] Text wrap in the organization filter.
- [ ]

**Comment by sriza** [comment]
Merged to main branch. Closed manually.
