### ISSUE TITLE
Issues from migration

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1196]
**Tasks**

- [x] Missing status in recipient_country_budget
- [x] Missing narrative in recipient region budget (recipient_region->0->narrative)
- [x] Result subelement language is filled even where there is no data
- [x] Humanitarian with 'false' value in default field values are not reflected in Activities
- [x] Languge being set in empty document link
- [x]  Existing organization's default value not shown in transaction.
