### ISSUE TITLE
Identification of File Format

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1212]
**Task**
- [x] Identify file format when user enters document url or uploads document in document link form

The following forms contain document link :
- [x] activity document link
- [x] result document link
- [x] indicator document link
- [x] indicator baseline document link
- [x] period target and actual document link
- [x] organization document link

**Comment by sarinasindurakar** [comment]
- [ ] When user enters the url which contains + sign it shows the following error  message.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/74f744ae-c529-4523-b4bd-3f414ec5afa7)

- [ ]  When user uploads the xlsb file , format is not selected.

**Comment by sarinasindurakar** [comment]
- [ ]  When user enters the  following url "it must be valid url" message is shown.
url : https://iatipublisher-prod.s3.amazonaws.com/aidstream-documents/'They-Say-Our-Work-Is-Not-Hala[…]tion-and-Care-in-Dadaab%2C-Kenya-20190904030948.pdf
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/fac9169f-a02a-49b3-b44f-111ad68cf607)

**Comment by sarinasindurakar** [comment]
- [ ] Those file which are uploaded in  other website are usually  shown as "Please ensure that url is correct and is publicly accessible" .
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/f2219594-9979-4595-a1cf-1c46de375df7)
Url:
http://sanadcomjo.com/homeEn.aspx
https://www.dggf.nl/file/download/56511572

**Comment by sarinasindurakar** [comment]
- [ ]   When user uploads xls ,doc, docx and xlsx file or adds the url, format is not shown.


![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/7a91b9e3-77f3-4336-9688-12921df6119c)

**Comment by sriza** [comment]
Merged to main branch. Closed manually
