### ISSUE TITLE
Default Value Extension

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#1213]
**Tasks**

- [ ] Add following fields to setting:

> - [ ] linked data uri ( needs discussion )
> - [ ] default collaboration type
> - [ ] default flow type
> - [ ] default finance type
> - [ ] default aid type
> - [ ] default tied status

- [x] Prefill the default values on creation of activity (manual, xls, csv and xml)
- [x] On publish xml file should have default values mentioned

**Discussions:**
1. If linked data uri must be included in the setting (since it was previously removed as it is about to be deprecated in next upgrade of IATI, reference : https://docs.google.com/spreadsheets/d/1AYj0Nn6StKUu2S23BIYa8o7OadWr_uJkFtuvWOtU5WU/edit#gid=788146062 )
2. Adding reporting org identifier, reporting org type, reporting org name and reporting org language in default values (these values are currently inherited from organization reporting org)

**Link to observation log:**
 https://docs.google.com/spreadsheets/d/1gFDfrA8sPtvpUjIsfg_eBgNTuXL1uJVM17HuszO-Ma0/edit#gid=0
 Row : 78

**Comment by praweshsth** [comment]
@DaveEade49 please look at this and give us your feedback on this.

**Comment by DaveEade49** [comment]
1. Sorry - can you expand on th issue here? - Are we saying we don't want to include on the xml as the value will be removed?
2. We should leave this as it is and update the user manual to reflect this ( also the help text )

**Comment by sriza** [comment]
@DaveEade49 

Regarding issue number 1, the linked data URI was initially placed within the setting of IATI Publisher, but later removed as it was to be deprecated in the next upgrade of IATI (discussion regarding this can be found at: https://docs.google.com/spreadsheets/d/1AYj0Nn6StKUu2S23BIYa8o7OadWr_uJkFtuvWOtU5WU/edit#gid=788146062). 

Thus, we are wondering if we are to include linked data URI in the setting during default value extension.
(If we decide on including linked data URI in the default values, we will include the value in the XML as well)

cc @praweshsth

**Comment by DaveEade49** [comment]
Hi, I think it would be wise to include it at the moment.
Thanks
David

David Eade | IATI Business and Data Analyst
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505 | M: +44 (7855 946589)
devinit.org<http://www.devinit.org/> | ***@***.***<https://twitter.com/devinitorg>
Sign up<https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f> to our newsletter and topic updates

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.
Development Initiatives Poverty Research America Inc, is a 501(c)3 charity registered in the US. Registration number 5737757. Registered Address: 1209 Orange Street, Wilmington, New Castle County, Delaware 19801, US.
DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives. If you have received this email in error, please delete it and notify the sender.

**Comment by sriza** [comment]
Merged to main branch. Closed manually
