### ISSUE TITLE
Automate sync of the org-id prefixes into Publisher from org-id.guide

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1342]
# Overview
Curently, the organization registration agency is solely sourced from the JSON file, and it doesn't receive updates when new organization agencies are added. Therefore, the Organization ID will now be automatically synchronized from organizationid.guide.
# QA Spec

- [x]  Regular schedule for syncing org-id prefixes to keep the data up-to-date.
- [x] The org-id prefixes retrieved from org-id.guide should be reflected in the Publisher database.

# Todo
- [x] Write a script that fetches organization registration agencies from org-id.guide, parses the organization registration agencies and updates current organization registration agency list. 
- [x] Write cronjob that executes script every day.

**Comment by sarinasindurakar** [comment]
- [ ] All organization registration agency is not shown in the organization level. Upon removing the country filter, the data in the organization registration agency dropdown is preserved, and it continues to show information according to the  previous applied filter.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/daf7f267-ba2b-45d9-b56c-9dc62f14f8f3)

**Comment by odscrachel** [comment]
Tested with the most up to date org-ids, but there aren't any recent additions. All seems fine though - if we notice any issues we can let you know.

**Comment by praweshsth** [comment]
cc: @dan-odsc 

Please review it in staging.

**Comment by emmajclegg** [comment]
@praweshsth - we've reviewed and are happy for this to be deployed in production.

**Comment by odscrachel** [comment]
A new org-id was added on Friday 'mg-nif' (https://github.com/org-id/register/pull/566) . This hasn't come through to publisher yet, is a daily cronjob running to check for changes? When should we expect the new registration agency code to be added?

**Comment by praweshsth** [comment]
@odscrachel We checked it and it is showing in the publisher. Yes, there is a cron job to update the list everyday, which runs at 00:00:00 UTC time.

**Comment by odscrachel** [comment]
Hi Prawesh, I can't see the MG-NIF option. When I choose MG- Madagascar I can only see MG-COA and then XI/XR identifiers. I've cleared cookies and checked a couple of browsers. 
![image](https://github.com/younginnovations/iatipublisher/assets/59564404/b2cb3c7e-6354-4284-aa20-8a2f7547ec48)

**Comment by emmajclegg** [comment]
To help with testing: SZ-CIT is an example of a new organisation identifier prefix added last week (https://org-id.guide/list/SZ-CIT). 

A new publisher needs this to register on IATI Publisher so can you let us know what's left to do on this issue? @PG-Momik @praweshsth . Thanks

**Comment by PG-Momik** [comment]
@emmajclegg 
Please have a read through this and let us know how we should proceed with current available solutions.

## Context:
- Organization Registration Agency drop-downs in Publisher uses a file called `OrganizationRegistrationAgency.json` as its source to display the list. 
- The solution to automatically sync IATI Publishers Organization Registration Agency list  is to simply fetch the latest Organization Registration Agency list from org-id.guide and update `OrganizationRegistrationAgency.json` via a Laravel command (script). 
- We wrote a simple script that reads the Organization Registration Agency from org-id.guide and overwrites existing `OrganizationRegistrationAgency.json` file, basically making sure that we have the latest Organization Registration Agency list in the system. 
- The idea here was to use Laravel's cronjob to execute the script at  24 hrs interval at 00:00 UTC everyday.

## Previous Problems:
1. Because of the way Publisher is deployed, it seems that the cronjob is not able to overwrite the existing `OrganizationRegistrationAgency.json`
2. To workaround  problem 1, we decided cache the updated list that we read from org-id.guide , and then read and display the updated Organization Registration Agency list  from cache. But this solution also failed, as the system clears cache at 8-12 hrs interval, even when we explicitly set cache for an indefinite period of time.
3. To workaround problem 2, we decided to write the updated list to S3 and then it  read from S3. 
4. Reading from S3 introduced a 2 new problems:
     - IATI publisher became slower
     - Unit test took nearly 3 times more time to complete. 
  
## Current Situation:

After an internal discussion with my senior devops colleagues, we've come up with 2 possible solutions:

**1. Read from available source**
  - This solution proposes to:
      -  Update organization registration agency in cache and S3 at 00:00 UTC
      -  Read organization registration agency from:
           - Cache (if updated values exists in cache)
           - S3 (if updated value does not exist in cache) 
  - A small problem with this solution is that the speed of IATI Publisher fluctuates. i.e if cached value exists the system is fast, if cached value doesn't exist the system is comparatively slower (.5 to 2.5 seconds for any page that has an organization registration agency drop down)

 - This solution has been tested but needs to be monitored for some days.

**2. Fix main issue of cronjob not being able to write to OrganizationRegistrationAgency,json**
- The solution seeks to fix the initial problem of cronjob not being able write to `OrganizationRegistrationAgency.json` directly.
- A slight problem with this solution is that initial attempts to do this have failed, and its difficult to estimate how long this solution will take as this needs to be studied, tested and monitored by the devops team.

**Comment by emmajclegg** [comment]
@PG-Momik , @praweshsth - I'll get a second opinion on this within the team and get back to you with comments.

As a short term workaround - is there a quick/manual way to add the new list SZ-CIT (https://org-id.guide/list/SZ-CIT) to the Publisher drop-down menu? We currently have an organisation that's blocked from registering.

**Comment by PG-Momik** [comment]
@emmajclegg 
I've deployed available solution 1 as the short term solution. This change has been deployed to production. Organization Identifier `SZ-CIT` is now available in production:
(Current UTC: 09:40 Wednesday, March 20, 2024)
![image](https://github.com/younginnovations/iatipublisher/assets/57512059/fd79bfee-075c-4051-90f2-f39afe523b93)

**Comment by odscjames** [comment]
Is the cache filled by any page loads that can't find the data, or is it only once a night? If it is the former, maybe the performance is ok, as only a few page loads will have to get the data from S3. Hopefully your monitoring will be telling you what is happening and we can check the performance.

I can think of a couple of other options to explore if the performance turns out not to be ok (putting lists in database, updating file in git repo regularly by GitHub action and relying on regular deploys to get this on server). However this would be a change in direction and we would need to evaluate how much time it would take.

**Comment by PG-Momik** [comment]
@odscjames 

> Is the cache filled by any page loads that can't find the data, or is it only once a night? 

I didn't understand this. 

For now we'll continue to monitor the change on production till March 25, 08:15 UTC at 8 hrs interval . We'll monitor for :
1. Check S3 file is being updated.
2. Check if drop-downs contain all Organization Registration Agency.

We'll  explore and work on other possible solutions if the changes we deployed do not work well. We'll close this issue if everything looks OK.

---

cc: @emmajclegg

**Comment by praweshsth** [comment]
This is working fine. We will not work on the solution no. 2 (Fix main issue of cronjob not being able to write to OrganizationRegistrationAgency,json) for now. You can close it, @emmajclegg if this is ok with you.

**Comment by emmajclegg** [comment]
Ok @praweshsth - I will close this issue for now and let you know if we notice any problems with future org-id prefixes.
