### ISSUE TITLE
Clearer auto-population of default "language" and "currency" on data entry screens

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1368]
Currently, users can specify and save a default _language_ and _currency_ in [Settings >> Default Values](https://iatipublisher-staging.yipl.com.np/setting). However, when they enter data against elements on the [Activity Data](https://iatipublisher-staging.yipl.com.np/activity/564) and [Organisation Data](https://iatipublisher-staging.yipl.com.np/organisation) pages, these attribute fields are not visibly auto-populated with the user's set default value.

For example - when entering an activity title (screenshot below), the language drop-down field is blank and the current default value is not obvious. Some users are repopulating this because they do not read the prompt text underneath the box.

![Capture d’écran, le 2024-02-09 à 16 12 52](https://github.com/younginnovations/iatipublisher/assets/137316374/4ed8ab2b-3af9-4943-84f5-78ca50b6aa72)

Similarly, with currency - the drop-down field is blank, the current default value is not obvious, and there is no mention of default value application in the text underneath. Users get confused and are repopulating this. 

![Capture d’écran, le 2024-02-09 à 16 16 17](https://github.com/younginnovations/iatipublisher/assets/137316374/a5aa293c-63ad-4ce4-93df-e63c980f47e9)

Can we visibly auto-populate _language_ and _currency_ fields with the user's set default value wherever they appear on data entry screens? Users should then only interact with the drop-down menu if they want to change the default value.

**Comment by praweshsth** [comment]
@emmajclegg @dan-odsc @robredpath @IsabelBirds 

The solution for this is to not populate the fields with the default values but just show the default language or currency because in case of populating default values in the form and if user only tries to add one of the many narratives or amounts in the same form but not the others, there will be validation error because the narratives or amounts are empty but the language and currency are not. Would that work ?

**Comment by emmajclegg** [comment]
@praweshsth - probably easiest if you discuss briefly on next week's call with @robredpath and @siwhitehouse as I'm not sure I follow entirely. This is all about what the user sees at the point of data entry and making it obvious to them that they don't need to repopulate "language" and "currency" each time they appear. 

Showing the current default value in the data entry box, without the user having to do anything, is what I mean. e.g. when a user adds their activity description, and their default language is set to English, they should see this:
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/76fc6658-c89d-45cf-a46a-fef38916c2f2)

**Comment by PG-Momik** [comment]
@emmajclegg 
We're proposing a similar idea to as presented on [comment](https://github.com/younginnovations/iatipublisher/issues/1368#issuecomment-1944304898)

# Summary
- Pre-fill default values field (language and currency). 
# Suggested changes

>*[Can we visibly auto-populate _language_ and _currency_ fields with the user's set default value wherever they appear on data entry screens? Users should the....](https://github.com/younginnovations/iatipublisher/issues/1368#issue-2127871405)* - emmajclengg

### Change 1 : Default values are displayed on filed ( not actually 'selected' )
- Because of the current validation in the system, elements like `title`, `sector`, etc that contain sub-element `narrative` cannot be saved if `narrative` is empty but `language` is selected.
- 'Auto-populating' by pre-filling/selecting the field (programatically) would result in users not being able to save the form as they would see validation errors, if they do not fill the adjacent field (narrative or amount).
- Modifying the existing validation rules would increase workload and potentially introduce new bugs
- This is why we recommend just displaying the default values in the field, but not actually selecting the default values in said field.
- This allows users to save the form even if the adjacent field is not filled.
- Likewise, if the adjacent filed are filled, default values will be save to db as well.
### Change 2 : Muted colors for default values
We also recommend changing the font colors for default values to muted color (color of placeholder text) because of the following inconsistency:
Imagine the following  scenarios:
- Scenario 1: 
	- Default language is not auto selected
	- User opens title edit form
	- Clicks on 'Add Additional Title'
	- Does not fill narrative
	- Selects language (say 'Ae')
	- Presses saves.
	- System throws validation error: "The narrative is required when language is specified."
-  Scenario 2: 
	- Default language is auto selected (in accordance to  **Change 1**), but there is no difference in font color
	- User opens title edit form
	- Clicks on 'Add Additional Title'
	- Language is auto selected (say 'En')
	- Does not fill narrative
	- Presses saves.
	- System does not throw a validation error.
- If there is no color to differentiate pre-filled default values vs normally selected values, there is UX inconsistency. 
# Tasks
- [ ] Study existing code that renders the form.
- [ ] Code level changes
	- [ ] Render the form with default values.
	- [ ] Handle user interaction with pre-filled values on form level.
- [ ] Test
# Expected Outcome
![ExpectedOutcome](https://github.com/younginnovations/iatipublisher/assets/57512059/4a892c86-0d93-4e73-b2ba-816880898b6b)

**Comment by IsabelBirds** [comment]
**1.** A general comment on the muted colour - we need to be careful about accessibility in terms of colour contrast. I'm not sure that muted grey would be legible to all users of our tool.

**Resources:**
* WCAG recommends a minimum colour contrast ratio https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
* Various tools can be used to check colour contrast e.g. https://webaim.org/resources/contrastchecker/

**2.** As a user, muted colours also often indicate to me that a field is disabled, meaning I cannot change the value within. 

A suggestion could be to use a background colour change instead. For example, this is the default behaviour on chrome browsers when autocompleting forms (shown below).

![image](https://github.com/younginnovations/iatipublisher/assets/44876111/35957924-24d8-4f14-bc27-c4cbae55ed99)

**Comment by emmajclegg** [comment]
Thanks @PG-Momik for the detail above.

> Change 1 : Default values are displayed on field ( not actually 'selected' )
>- Because of the current validation in the system, elements like title, sector, etc that contain sub-element narrative cannot be saved if narrative is empty but language is selected.
>- 'Auto-populating' by pre-filling/selecting the field (programatically) would result in users not being able to save the form as they would see validation errors, if they do not fill the adjacent field (narrative or amount).
>- Modifying the existing validation rules would increase workload and potentially introduce new bugs
>- This is why we recommend just displaying the default values in the field, but not actually selecting the default values in said field.
>- This allows users to save the form even if the adjacent field is not filled.
>- Likewise, if the adjacent filed are filled, default values will be save to db as well.

This sounds fine. Auto-populate was perhaps the wrong word to use - like you say, we want the default value clearly displayed to the user. 

> Change 2 : Muted colors for default values

To take on Isabel's point, let's avoid using muted font colour for accessibility reasons. Can a different background colour be used in the field instead? (like Isabel's Chrome example above). 

I agree we want to distinguish pre-filled default values from normally selected values. But in a way that suggests to the user that the default value field is still editable (if they want to change it) rather than disabled.

**Comment by sarinasindurakar** [comment]
@A4family 

- [ ] Issue 1:  When the user attempts to save the form after adding the same default value language in another narrative language, and one narrative language remains unselected while its default value matches what the user has added, a '500 Server Error' is displayed.

https://github.com/younginnovations/iatipublisher/assets/65848732/be859127-e706-486a-9e97-0e33fd39803d

**Comment by sarinasindurakar** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
HI @sarinasindurakar - can I check what changes are in staging exactly?

I've only looked at the data entry screens for "Add activity" and _description_, but don't see a default language displayed.

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/bb0d8909-7702-4b14-bc58-0d2f28d6e328)

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/a0b1b813-9123-4d51-bba8-afd7297e653d)

**Comment by PG-Momik** [comment]
@emmajclegg 

This seems to be working on staging.


![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/e66cc23c-6184-4339-a1b1-afcb344794a7)



![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/c4d43697-e245-489d-976a-e4f4fe239e77)



Please make sure that you've filled the default language, via Settings page >> Default values tab first.


![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/05928f8c-0da8-46c6-9ca5-4b5baef22053)


If it still doesn't work for you, could you list out the steps involved to recreate the issue. (along with the publisher id)

**Comment by emmajclegg** [comment]
@PG-Momik - this looks fine now, sorry it may have been me not saving the default values properly.

The auto-display of language and currency on the various data entry screens looks great - it's much clearer to users now.

So clear, that I think most of the prompt text underneath the drop-downs is no longer needed - what do you think?

e.g. the text below, while entering an [activity transaction](https://iatipublisher-staging.yipl.com.np/activity/934/transaction/6775/edit), doesn't seem to add much as the user has to select a value on the Currency codelist (they have no other option but to use the drop-down menu):

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/39de782d-1732-4a39-90a0-fd9511f8d43f)

And here, editing an [organisation name](https://iatipublisher-staging.yipl.com.np/organisation/name), it's very obvious now that the default is being assumed:

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/deef22d2-a7fd-4865-b00a-ee9b2c284e50)

I've started a discussion [here](https://github.com/younginnovations/iatipublisher/discussions/1420) on how we review user-facing text more generally across IATI Publisher, but this might be a good opportunity to remove prompts that are no longer needed.

**Comment by emmajclegg** [comment]
Also - could you check the colour contrast ratio of the new auto-display fields for accessibility? e.g. using a site like https://webaim.org/resources/contrastchecker/ to check whether the grey text on green background meets minimum requirements, and so is easy to see by users

**Comment by PG-Momik** [comment]
@emmajclegg 

 > So clear, that I think most of the prompt text underneath the drop-downs is no longer needed - what do you think?

A concern raised against this point is that users might get confused as to why default values are appearing on the fields if no help text are present. Some alternatives for this is:
1. Change help text to "Default value selected. Selected value can be changed." if default values are set.
2. Remove verbose messaging and display 'Help' text similar to other fields. 
3. Make no change at all. Since some texts might change after the discussion #1420 , the current help messages for default value field might change to something shorter and meaningful.

**Comment by PG-Momik** [comment]
@emmajclegg 
Regarding the contrast ratio 

With the current color combinations:
Font color hex: #68797E
Background color: #F0FFFF
Ratio: 4.42:1


![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/bc6e48c5-aac3-419b-b089-9c6d5fae7559)


### Change

I've changed the font color to: #155366 (This color hex is already available in the design)


Which gives the result:

![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/96cba956-5913-48b2-bafe-9ea199b7d127)



### Preview:

![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/515e7d7d-ab95-46de-85c5-2159664796cb)



This change has been deployed to staging.

**Comment by emmajclegg** [comment]
@PG-Momik - thanks for the comments.

>A concern raised against this point is that users might get confused as to why default values are appearing on the fields if no help text are present. Some alternatives for this is:

I don't think there will be confusion but, with that in mind, can I suggest the wording below for the help text underneath data entry boxes:

"If no language is selected, your default language is assumed." - for language fields
"If no currency is selected, your default currency is assumed." - for currency fields

This is similar to wording you've already got in places, and it removes any chance of confusion as to what the "value" is we're referring to. Standardising this prompt text across the language and currency fields can be a first step towards #1420 .

**Comment by PG-Momik** [comment]
> "If no language is selected, your default language is assumed." - for language fields
> "If no currency is selected, your default currency is assumed." - for currency fields

This has been deployed to staging.

**Comment by PG-Momik** [comment]
This has been deployed to production.
