### ISSUE TITLE
Add clearer user messaging in Publishing Settings when the publisher's Registry account is pending approval

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1369]
Can we add a clearer message to users when their IATI Registry publisher account is pending approval (i.e. the API link with IATI Publisher is not established yet), rather than labelling the API token as "Incorrect"?

### Current workflow
(please clarify if this is not accurate)

**When a new publisher registers with IATI for the first time within IATI Publisher:**
- a new publisher account is created in the IATI Registry, pending approval by a Registry admin
- an API token is created and automatically populated in [Settings >> Publishing Settings](https://iatipublisher-staging.yipl.com.np/setting)
- the API token is labelled "Correct" (Green):
![Capture d’écran, le 2024-02-09 à 16 57 02](https://github.com/younginnovations/iatipublisher/assets/137316374/b15a8a68-831a-45cc-ba3d-9a410cef0a77)

**The user then:**
- Browses to [Settings >> Publishing Settings](https://iatipublisher-staging.yipl.com.np/setting)
- Is shown that the API token is "Correct"
- May or may not press "Verify"
- If they do press "Verify", IATI Publisher tests the connection to the Registry and labels the API token as "Incorrect" (red) if the publisher's Registry account is still pending approval:
![Capture d’écran, le 2024-02-09 à 16 56 38](https://github.com/younginnovations/iatipublisher/assets/137316374/346b6710-37a8-4fc1-8d9e-4cfb678af638)

The current set up can be confusing if the user does not realise that their account is pending approval. Can a new API token label (e.g. "Pending approval") replace "Incorrect" in this case? And/or the Publishing Settings fields be frozen to stop the user interacting with them unnecessarily?

**Comment by PG-Momik** [comment]
@emmajclegg 
Sure, we can change how api token status is displayed.

# Summary
- Show status `pending` when api token is correct but pending approval.
# Tasks
- [ ] Study existing code that handles token verification against registry. Study response from registry
- [ ] Code level changes
	- [ ] Handle response from registry api
	- [ ] Change response on `/verify`  endpoint in publisher (backend)
	- [ ] Handle changed response on publisher (frontend)
- [ ] Test

**Comment by sarinasindurakar** [comment]
- [ ]  Can we use this color for pending approval  toast message?
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/bb9f2a01-c0b6-470c-9d71-729b38078c83)

- [ ]  The error API toast message appears in green, whereas the accurate toast message is displayed in red. Conversely, the incorrect API token message should be shown in red, while the correct toast message should be displayed in green.
![image (22)](https://github.com/younginnovations/iatipublisher/assets/65848732/205d1b64-d368-4402-bd2b-1f6a332c16de)
![image (21)](https://github.com/younginnovations/iatipublisher/assets/65848732/06157512-8802-42bc-a8c6-8cc31707d313)

- [ ] The pending tag is difficult to read.  Change the background color of the tag to a darker shade.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/4953807a-b4da-43f0-921d-be13caea3144)

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - I've tested in staging and the API token status looks to be working as expected. I'll check with the wider Support team for feedback and comment again tomorrow (e.g. I'll suggest slightly different wording for the warning message below)

![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/336f8075-fdc9-42c9-bf58-6874dff3d628)


One question - once the publisher account has been approved on the IATI Registry, I noticed that the "Publisher is inactive" alert on the Activity Data page disappeared straight away, and without me having to do anything as a user (which is great).

_Before publisher account approved:_
![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/909eb69c-64e6-4a6b-96b8-b32bf116f4af)

_After publisher account approved:_
![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/2f69c182-b5d8-4bad-a9e6-7c3b3ecc576b)


On the Settings page, to change the API token status from "Pending" to "Correct", it looks like the user has to know to click the "Verify" button?

_After publisher account approved:_
![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/13099b41-060c-43a7-8ef1-6327856d29f7)

_After clicking "Verify":_
![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/8f2341bb-5892-4672-829e-9b85ed1705d4)

Theoretically, is there a way way for the API token to be checked automatically when the user visits the Settings page? So that it doesn't look like something is still pending to users.

**Comment by PG-Momik** [comment]
@emmajclegg 

>  I'll suggest slightly different wording for the warning message below

Could you give us an appropriate message for the toast message. 

> Theoretically,  is there a way way for the API token to be checked automatically

Yes this can be done.

**Comment by emmajclegg** [comment]
>Could you give us an appropriate message for the toast message.

Current wording: "Please make sure that your publisher is approved in IATI Registry"
Suggested wording: "Your account is pending approval by the IATI team - someone should be in touch within two working days"

(this is to make it clearer to the user that they don't have to do anything, they're just waiting on us in Support)

>Edit: I've made changes to check for publisher status on page load. Since checking for publisher status via the registry API takes longer than reading from db, I've added a loader on the token field. Let us know if anything needs to be changed.

Amazing! Looks to work well, thanks

**Comment by praweshsth** [comment]
> Suggested wording: "Your account is pending approval by the IATI team - someone should be in touch within two working days" 

This has been done. 

@emmajclegg
