### ISSUE TITLE
Classify "recommended" vs. "optional" default values for activities on the Settings page

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1371]
Currently, users are being prompted to complete all fields on the [Settings](https://publisher.iatistandard.org/setting) >> Default Values page by a "Complete your setup" alert. 
<img width="282" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/9d18132b-bc77-490a-8be8-f4f13fa56381">

Not all of the default values are necessary to publish, or relevant to all publishers, so we would like to change some of them to optional.

1) Can we split the "Default for activity data" into two sections on the Defaults Values data entry page - "Recommended defaults for activity data" and "Optional defaults for activity data". 

2) Can the following elements be listed under "Optional defaults for activity data", and this section be moved to the bottom of the data entry page (below recommended defaults):
- Linked Data URI
- Budget Not Provided 
- Collaboration Type

3) Changes to the "Complete your setup alert" - raised under a separate GitHub issue: #1372 

![image](https://github.com/younginnovations/iatipublisher/assets/137316374/8c113f6f-efe6-4dff-961b-77d08a9089df)

**Comment by PG-Momik** [comment]
@emmajclegg  
Yes we can split the settings>>default values form into 2 parts. 
# Summary
1. Form will be split into 2 parts, namely "Recommended defaults for activity data" and "Optional defaults for activity data".
2. Recommended default for activity data will contain the following elements:
	- Default Hierarchy
	- Humanitarian
	- Default Flow Type
	- Default Finance Type
	- Default Aid Type
	- Default Tied Status
 3. Optional defaults for activity data will contain the following activities 
	- Budget Not Provided
	- Linked Data URI
	- Default Collaboration Type

> [!NOTE]
> - Only visual changes will occur i.e no data level changes need to be made
> - No changes to the buttons will be made i.e even tho the form is split (visually) they will share the same save/cancel button.
# Tasks
- [ ] Look at existing code that renders settings >> default values form
- [ ] Code level changes
	- [ ] Remove 
	- [ ] Add Recommended default
	- [ ] Add Optional defaults
- [ ] Test

**Comment by emmajclegg** [comment]
@PG-Momik - thanks, yes your summary makes sense to me.

To note, I'm not suggesting any changes to the "Default for all data" section (which includes Default Currency and Default Language at the top of the data entry page). This works well and can stay where it is.

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging.

While working on I've come to realize that changes made from this must also be reflected on Organization listing page, especifically :
1. Default values status
![image](https://github.com/younginnovations/iatipublisher/assets/57512059/f9d13875-3f86-4646-8c10-21aef5476aa7)

2. Filter
![image](https://github.com/younginnovations/iatipublisher/assets/57512059/958a61aa-660a-4ca2-a687-69a8f61eb807)

Previous estimations didn't account for these changes, should we work on this now or should a new issue be raised ?

**Comment by emmajclegg** [comment]
Hi @PG-Momik - thanks for flagging this. We recently put wider work on the Organisation List admin page on hold as us in IATI Support need to think through how we want to use it and issues affecting end users in Publisher are more of a priority for us at the moment. I'll make a note of this in the (paused) GitHub issue #1280 about the Admin interface so we don't forget, but there's no need to make any changes to the Organisation List page yet.

It would be good to clarify how the default values flag is currently working, just so we understand (I assume all default values, recommended and optional, need to be completed for the completeness label to display green, like in the example below?)


![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/2b50af1b-9cf9-431e-be77-604814ec369d)

**Comment by emmajclegg** [comment]
To flag - looking at the Default Values page again in staging, I've noticed the question marks with hover-over guidance have disappeared in the activity data defaults sections:



![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/e3595228-9718-4d73-8aed-2d05f892083c)

**Comment by sarinasindurakar** [comment]
@emmajclegg This has been resolved and deployed to staging.
