### ISSUE TITLE
Update the default value completeness alert to exclude optional defaults

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1372]
Following on from issue #1371 , can we review what triggers display of the "Update default values" alert to users. Default value elements which we are now classing as "optional" (Linked Data URI, Budget Not Provided, Collaboration Type) should be removed from the trigger.
<img width="282" alt="image" src="https://github.com/younginnovations/iatipublisher/assets/137316374/01367e70-10eb-40f2-8ecb-0888ac6ac14b">

This is to remove some of the friction to publishing and avoid users populating these defaults unnecessarily.

Ideally, whatever inclusion/exclusion flag we set up against these elements should allow easy adjustments to the trigger and default values alert in future.

**Comment by PG-Momik** [comment]
@emmajclegg 
Yes, we can change the logic to display "update default values" alert on the activities listing page.
# Summary
- Only show the 'Complete your setup' alert when any elements in "Recommended default" (see issue #1371) is empty.
# Tasks
- [ ] Study existing code  that calculates default values completeness
- [ ] Code level changes
	- [ ] Change the logic to determine default values completeness by not accounting for elements in  "Optional defaults"
- [ ] Test

**Comment by PG-Momik** [comment]
@emmajclegg We've deployed this to stage. 

> [!NOTE]
This change is not currently working on stage and dev because the CKAN key does not seem to be working.

**Comment by emmajclegg** [comment]
@praweshsth updated us today on the issue with the Registry staging API token that Young Innovations is using - we've put him in touch with our contact (Cormac) who manages the Registry to troubleshoot it. I understand it means we can't test this change to the default values alert on Publisher staging, so this is paused until the Registry link is resolved.

**Comment by sarinasindurakar** [comment]
@emmajclegg  The issue regarding the Registry staging API token has been resolved. We have generated and used a new API token for dev and stage environment. Please let us know if any changes are required for the default value completeness alert.

**Comment by emmajclegg** [comment]
That's good news @sarinasindurakar. I've checked the default value completeness alert in staging and it looks to be working as expected, thanks. I've added a comment on this issue about missing hover-over guidance I noticed: [#1371](https://github.com/younginnovations/iatipublisher/issues/1371)

**Comment by emmajclegg** [comment]
One comment on this before we deploy - can we update the completeness alert messaging so that it is clearer to users which values they now need to complete for the alert to disappear?


![Image](https://github.com/younginnovations/iatipublisher/assets/137316374/0b381474-d56d-4a64-b750-3d6daedf4848)

**Current wording:** Update default values
**Suggested wording:** Complete default values (currency, language and recommended defaults for activity data)

**Comment by PG-Momik** [comment]
@emmajclegg 
Static message "**Update default values**" has been replaced with "**Complete default values (currency, language and recommended defaults for activity data)**" and deployed to staging. 
Current view: 


![Image](https://github.com/younginnovations/iatipublisher/assets/57512059/5f0fd457-fbce-43c8-843e-b036ff3955f2)

**Comment by praweshsth** [comment]
Deployed in production
