### ISSUE TITLE
Organisation Module

### ISSUE THREAD

**Issue by Man0zZ** [younginnovations/iatipublisher#144]
**Tasks**
- [x] organisation data UI
- [x] Organization Add and Edit
- [x] Dynamic Detail Page

**Comment by man-git007** [comment]
@sriza @Man0zZ Is this issue completed?

cc @SauravSilwal10

**Comment by sriza** [comment]
@man-git007 The tasks related to this issue have been completed.
