### ISSUE TITLE
Increase activity bulk publishing limit from 10 to 100

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1480]
# Tasks
- [x] Review the load testing
- [x] #1557
- [x] Changes required in front-end: (Implement a selection feature that allows users to select more than 10 activities.)
- [x] Changes required in back-end: 
    - Implement bulk validate to reduce bulk publish time. 
- [x] Development
- [x] Test with variable payloads: 50T, 10R->5I->5P
- [x] Deploy
- [ ] Monitor until Nov 29th, 2024. Then close this userstory.

---

Follow on from this investigation: [#1408](https://github.com/younginnovations/iatipublisher/issues/1408)

**User story:** As a user of an organisation with 10-100 activities, I want to be able to republish all my activities in bulk after making changes, so that I can save time.

**Considerations:**
- We already have two organisations on IATI Publisher with more than 100 activities, and evidence from one that the current bulk publishing limit creates extra work for them.
- We are considering migrating many more organisations from AidStream that have more than 100 activities.
- We want to avoid a hard activity limit on IATI Publisher, whilst ensuring that it remains targeted to small to medium-sized organisations (there is no reason to consider a bulk publishing limit above 100 as stands)

**Comment by emmajclegg** [comment]
@PG-Momik - I've reported it , thanks

**Comment by PG-Momik** [comment]
@emmajclegg thanks,,

**Comment by emmajclegg** [comment]
It should be fixed @PG-Momik

**Comment by PG-Momik** [comment]
@emmajclegg yes it has been fixed.

**Comment by subash-cm** [comment]
@PG-Momik 

- [ ] 1. S.N is not serially updated from page 2. (In page 1, there are 100 activities, but on page 2, it starts from 11)
- [ ] 2. User should be restricted to select more than 100 activities

![image](https://github.com/user-attachments/assets/b7247b4b-aa44-4982-9370-ccb888bc5e25)

- [ ] 3. For 50T, 10R->5I->5P, 500 server error occurred while getting validation status
![image](https://github.com/user-attachments/assets/8b4ab2d6-ba80-4c18-ba27-1a6915eebf97)

**Comment by Sanam-07** [comment]
- [ ] Issue 5: The Internal Server Error is being displayed when the user try to bulk publish 50 Heavy activity.
![image](https://github.com/user-attachments/assets/c9af683f-f51b-4845-b4c9-26925fb7bdb4)
![image](https://github.com/user-attachments/assets/efffbcc3-b8fc-4252-b469-267f86e36d35)

**Comment by emmajclegg** [comment]
@PG-Momik - to summarise after today's call,

- you have resolved the IATI Validator error mapping issue by successfully sending individual activities to be validated in parallel (let me know if that's not the case)
- there are processing problems still being experienced when bulk publishing "heavy" activities 

Suggested action:
- impose a 20MB file limit size that prevents the user from bulk publishing an activity file above that size (the limit could be lower if necessary, which would still accommodate the majority of users. It was mentioned in issue #1557 that very few files on the IATI Registry are larger than 20MB)

**Comment by PG-Momik** [comment]
@emma This has been deployed to staging.

We've increased count of activities displayed in the listing page from 10 to 25. Moving to next page still holds selection from previous page. (we can do 25+ 25). 

> [!NOTE]
> - For testing: I've cloned 100 activities for the publisher: My organisation Z
> - For testing : You an duplicate any activity using its activity id. 
         Use this temporary API: `iatipublisher-staging.yipl.com.np/duplicate-activity?activity_id=<id>&no_of_iterations=<iterations>` .
         Example: https://iatipublisher-staging.yipl.com.np/duplicate-activity?activity_id=1110&no_of_iterations=10

**Comment by emmajclegg** [comment]
Thanks @PG-Momik - I'll carry on looking at this tomorrow.

For awareness, has a file size limit been applied? i.e. will the user be prevented from trying to publish 100 "heavy" activities above a certain threshold?

**Comment by PG-Momik** [comment]
@emmajclegg Yes. Max size limit of 20MB has been implemented.

**Comment by emmajclegg** [comment]
Thanks. A few comments:

1) **Bulk publishing** - I haven't tried to test the limits with very heavy activities, but this looks to be working well.

From talking to my team today, we think 15 minutes is probably the longest we would expect a user to wait while publication takes place (before they probably think something is wrong and contact us for help!). From your testing, do you have an idea of how likely it is for publication to take longer than that, and is there any risk that the user could freeze and crash the tool from trying to publish too much?

This is to check whether we should be applying a lower data limit than 20MB. I'd prefer to stop a user publishing 100 activities at once if there's any chance that they won't be able to complete the action successfully.


2) **Activity selection** - I've noticed that switching between the activity status buttons loses any activity selection that the user has already made.

Example: I click "Ready for republishing" and select 2 activities in that list:
![Image](https://github.com/user-attachments/assets/1ae88c97-85d4-401e-98ff-975b82119430)

I then click "Draft" to select more activities, but the previous selection has been lost:
![Image](https://github.com/user-attachments/assets/661d2f12-f3a7-4cf9-9d86-8c43796fd930)

**Comment by PG-Momik** [comment]
@emmajclegg  Update on this as well:

1. Heres how the error screen appears on reaching max size:
 ![Image](https://github.com/user-attachments/assets/6cd60eb7-09a9-4c29-a513-6f6b72b5c8c4)
![Image](https://github.com/user-attachments/assets/5a15f84e-d71e-4dd9-bd72-3add3710d3ba)
(The cummilative filesize is being calculated on the core elements completion check)

2. Regarding the bulk publish times, most test durations have been under 15 minutes. However, with heavy data, we had observed times ranging from 24 to 32 minutes and occasional crashes on different environments (these have not been faced after we implemented the 20MB max limit).

3.  > I've noticed that switching between the activity status buttons loses any activity selection that the user has already made.

We'll work on the necessary changes required to maintain state even when filter is changed.

**Comment by emmajclegg** [comment]
@PG-Momik - to check, has the max file size been implemented based on the amount of data the user is trying to publish in one action (i.e. 100 activities), or on how large their activity file will be after they have published? (which may include more than 100 activities).

If a user did receive the error message in your screenshot and contacted support, I'm trying to understand what action we would take, depending on whether they have reached the limit of using IATI Publisher vs. just reached the limit of the bulk publishing process.

**Comment by PG-Momik** [comment]
> is that correct?

Yes, that's correct.

> Does a limit also need to be placed on the amount of data the user is trying to add to the activity file in one action 

As for whether a limit should be placed on the amount of data the user can add to the activity file in one action, I don't think it's absolutely necessary. However, implementing a file size limit at that level would be simple—it would just be adding a simple check on the existing checks.

> are you not worried about that affecting performance?

When it comes to performance, we're more concerned about the number of users trying to publish at the same time, rather than the data volume itself. With a single worker queue, the availability of that queue directly impacts wait times. The more bulk publish processes there are, the longer the wait times will be.

---

With this, I think it's best to evaluate how the 100-item bulk publish performs in practice and observe any actual errors users might encounter.

**Comment by emmajclegg** [comment]
> As for whether a limit should be placed on the amount of data the user can add to the activity file in one action, I don't think it's absolutely necessary. However, implementing a file size limit at that level would be simple—it would just be adding a simple check on the existing checks.

If a limit is simple to add, I would suggest applying one just in case a user bulk publishes something unpredictable. I'll defer to you on what a sensible limit would be.

> With this, I think it's best to evaluate how the 100-item bulk publish performs in practice and observe any actual errors users might encounter.

Yes, agreed - I'm happy to move ahead implementing this when ready and monitor performance with existing users. Queue times for publishing are something to keep an eye on in future as we move more users to the tool.

**Comment by PG-Momik** [comment]
@emmajclegg 
This has been deployed to staging.  Here's how the error screens look:

(For batch max limit error at 4MB)
![Image](https://github.com/user-attachments/assets/8cb5bd12-c22f-45a4-aca5-03a0e79c6996)

(For org max limit at 20MB)
![Image](https://github.com/user-attachments/assets/6beff9f4-9b34-4234-b110-b0ac93b09d18)

**Comment by Sanam-07** [comment]
- [ ]  Issue : Getting Server error when trying to bulk publish the activities.
![image](https://github.com/user-attachments/assets/24149872-2e72-4de9-8645-527cdcbec91e)

**Comment by emmajclegg** [comment]
@PG-Momik - I'm reopening as I suspect there's an issue with this deployment.

Any activities I try to publish from various staging test accounts encounter the error below at the core completeness check stage:

![image](https://github.com/user-attachments/assets/176659f1-cff7-4e0f-bcea-4fe50fa9190f)

We've also had a user report it in the live environment: https://iati.zendesk.com/agent/tickets/45745

This is preventing publication at the moment, so please can be rollback the changes as soon as possible if that is the easiest way to resolve

**Comment by PG-Momik** [comment]
@emmajclegg 
Fixed and deployed to prod. 
The issue was caused by a mismatch in parameter types introduced during changes made for Codefactor suggestions (Codefactor is a code quality check tool). We didn’t catch the issue in production earlier because we cannot test publish feature on prod. Unfortunately, I didn't detect the issue during the code review as well. Sorry for the inconvenience caused.

**Comment by emmajclegg** [comment]
@PG-Momik - I appreciate you looking at this. I'm not convinced the issue is fixed so I suggest waiting until tomorrow, then can you and the team take more time to test it properly.
 
I've tried to publish a single activity from two different test accounts on IATI Publisher staging. Each time I try to publish, it now hangs on the following screen:
![Image](https://github.com/user-attachments/assets/aec78225-d1e1-4cc1-b9ca-85c98dcd9f93)

I haven't seen it progress to the step, despite 10 mins+ of waiting.

I also can't test publishing on the live site, but assume there's likely to be the same issue.

**Comment by PG-Momik** [comment]
Hi @emmajclegg,

The fix deployed yesterday allowed me to successfully publish some test data from my local machine. Today during our testing, we didn’t encounter the issue you described on both stage and dev environments. I reviewed the logs for the specific error you faced, and while there were logs, the issue shouldn’t have been possible since the fix had already been pushed and deployed and the code causing the issue didnt around that time.

It’s possible that Laravel retained some app level cache, which could have caused the issue to persist. To address this, I’ve cleared all app-level caches in production using `php artisan optimize:clear` (this command clears all app level caches).

Let’s keep this issue open until we can confirm that BP is working as expected in production.

**Comment by PG-Momik** [comment]
@emmajclegg 
> UPDATE: Having tested this later in the day, the issue I describe below may have resolved itself (for the activity in the screenshot at least)

I hadn’t seen the updated text earlier but it's great to know that it was working. 

If the issue still persists in prod, we'll look into rolling back the recent changes.

**Comment by emmajclegg** [comment]
Hi @PG-Momik - I've tested single and bulk publishing on staging and, as far as I can see, there's no further issues thanks. I'll let you know if users report anything else.
