### ISSUE TITLE
Guide new users through data entry screens in the right order

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1487]
When first logging into IATI Publisher after registering an organisation, a user is shown the Activity Data screen with no information on what to do first:

![image](https://github.com/user-attachments/assets/ad85c600-143b-4886-90ae-fe5bd6d26c6a)

Can we show new users some simple prompts (e.g. like AidStream's below), advising the order to complete steps in:
1) Complete Publishing Settings (if the account needs linking to the IATI Registry)
2) Complete Default Values
3) Complete and publish Organisation Data
4) Create an activity

![image](https://github.com/user-attachments/assets/b551ba82-2c2e-42e9-a1ff-d4fc8c536954)

# Tasks
- [ ] #1521
- [x] #1534
- [ ] #1535

**Comment by shreyaydi** [comment]
@emmajclegg We’ve designed the user guidance for first-time users. Please take a look at this issue. #1521

**Comment by asminashrestha** [comment]
@emmajclegg Please have a look at the updated the design for the user guidance for first-time users. #1521

**Comment by emmajclegg** [comment]
I've commented in #1521 and happy for this to move into development work

**Comment by Yash-ftW** [comment]
Development and testing has been paused. Can't work on step 1 (validating token) because IATI registry staging is down (#1564)

CC: @BibhaT  @PG-Momik @emmajclegg

**Comment by emmajclegg** [comment]
The IATI Registry staging site should be back up @Yash-ftW. I've replied to @PG-Momik here how to report it in future: https://github.com/younginnovations/iatipublisher/issues/1564

**Comment by Yash-ftW** [comment]
Thank you @emmajclegg

**Comment by subash-cm** [comment]
@Yash-ftW  Here are some UI and functional issues as of now:

**UI Issues**

- [ ] 1. Emoji is not displayed on Onboarding screen

![image](https://github.com/user-attachments/assets/01a93acc-73cd-487c-802c-a65dc41abf61)

- [ ] 2. Buttons width and height are not as per figma design

![image](https://github.com/user-attachments/assets/3b32b733-fc17-4097-af34-dbc389b8335d)


- [ ] 3. Step 2 > Change "Default for all values" to "Default for all data" as per figma

![image](https://github.com/user-attachments/assets/fa4a6f3f-bcd2-40b8-9e92-6255331df7b2)

- [ ] 4. TBD: Once the onboarding modal is closed, where can the user access it?

- [ ] 4. "Previous" button is not aligned properly

![image](https://github.com/user-attachments/assets/618b6acd-8249-40f4-aae2-f746f20b6390)

- [ ] 5. Step 2 > Remove "*" on all fields

- [ ] 6. Step 3 > Button label should be "PUBLISH And NEXT"

![image](https://github.com/user-attachments/assets/ce5ccb13-335c-4046-94c4-c9d0e904040d)

- [ ] 7. On all steps, Info text /Input field section should be aligned in middle as per figma design

![image](https://github.com/user-attachments/assets/189328fd-c8d5-40ab-ae24-c2866264fef5)

- [ ] 8. The font size of texts below Welcome message is not as per figma design

![image](https://github.com/user-attachments/assets/e5f3944d-863e-4e9d-a065-b2415abc51d2)

- [ ] 9. If user navigates back to completed step, there is no indication of active steps on sidebar

![image](https://github.com/user-attachments/assets/7fbc7e3b-cae4-4522-8c73-34e2ba7088d2)

- [ ] 10. The size of Tick sign is smaller than that of figma design in both sidebar and success message

![image](https://github.com/user-attachments/assets/ea4510cb-289e-450a-beb4-6e4098272e81)

- [ ] 11. After save and next on step 2, display success text for little longer time.
- [ ]  12. Success text is not displayed after Save and Next on Step 3.
- [ ]  13. Remove "*" sign on secondary-reporter field (As per figma)

![image](https://github.com/user-attachments/assets/7bb796bd-0d9c-4041-bd75-548e166d0d29)


**Functional Issues**

- [ ] 14. After completing the step, when user goes to next page and navigate back to previously completed step, and removes all values and Save, the "completed" indication should not be displayed


https://github.com/user-attachments/assets/93d01a66-2ede-41be-863a-7f7868e5dac1



- [ ] 15.  Step 3 > For invalid reference, display the validation message on frontend

![image](https://github.com/user-attachments/assets/6f0a7f4f-b984-4dbe-8e8b-d40952894b56)

- [ ] 16. User should be able to navigate to different step from sidebar

**Comment by subash-cm** [comment]
@Yash-ftW 

After completion of step 2 or 3, if user navigate to 'settings' page and then navigate back, the complete state is not visible. (Form should not be displayed once completed)

**Comment by subash-cm** [comment]
Org registered to IATI case:  @Sanilblank @Yash-ftW 

- [ ] 1. When a publisher is not verified, and token status is pending, if Step 1 "Publishing Setting" is saved, the completed message is displayed, but after the refresh, the complete state is gone and the new form is displayed.


https://github.com/user-attachments/assets/ea3d25de-c418-4290-a55b-dccb081587cd


- [ ] 2. When the user logins for 1st time, 4th step is displayed as "Completed"

- [ ] 3. Restrict the user from saving API token when it is incorrect


https://github.com/user-attachments/assets/92b2bd09-2c8d-4d93-942a-0261d3e1a123

**Comment by subash-cm** [comment]
publisher_verification is not updated after Save and Next

**Comment by emmajclegg** [comment]
Thanks @Yash-ftW. This is looking good.

**One observation:**

- Can we ensure that the "Get Started" option remains available in the Profile menu for all users? (from what I can see, it's disappearing once I've completed steps 1-4 of the walkthrough). It may be useful for users to refer back to, even if they have completed the steps (e.g. if they are helping others users), so there's no harm leaving it as a menu option.

I see this as separate to the "Don't show this again" tickbox in the walkthrough, which I understand stops the walkthrough from appearing on screen next time the user logs in if they have uncompleted steps (is that correct?). This makes sense and looks to be working as expected if so.

![Image](https://github.com/user-attachments/assets/f21151f5-3f5a-4526-b11f-19cc41b9fc6a)


**Two minor changes to wording for clarity:**
1) Label Step 4 "Activity Data", for consistency with the other step titles
![Image](https://github.com/user-attachments/assets/5851419a-55e9-465b-951a-bed3869f5466)

2) Simplify Step 1 completion message to "Publishing settings completed" 
![Image](https://github.com/user-attachments/assets/a1aa45a8-4623-4c92-be83-06b7574b28db)

**Comment by Yash-ftW** [comment]
> Can we make sure Step 1 (org already registered with IATI) text matches the [Figma design](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=14921%3A37626&node-id=15062-29319&viewport=161%2C-1010%2C0.24&t=UXrqgWX4Gidk8N7B-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=15062%3A29319) (i.e. includes "how to create an API token" link if relevant)

@emmajclegg Regarding this, we currently do not have a resource/manual of any sort that is relevant for 'how to create an API token'. Where should users be redirected to ?

**Comment by emmajclegg** [comment]
@Yash-ftW - ok, no need to add the "how to create an API token" link in that case.

**Comment by Yash-ftW** [comment]
@emmajclegg , Changes have been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @Yash-ftW.

Flagging one typo on the screen below (it should read "Generate **an** API token..."), but otherwise all looking good to go. Thanks

![Image](https://github.com/user-attachments/assets/46450afa-1212-4722-bb84-fdb03b3c3a20)

**Comment by Yash-ftW** [comment]
@emmajclegg, This has been deployed to production with the typo fix.
