### ISSUE TITLE
[BE] Bulk import changes - Basic activity sheet

### ISSUE THREAD

**Issue by PG-Momik** [younginnovations/iatipublisher#1524]
# Tasks
- [ ] Change download activity template file
- [ ] Update api to accept new import file without transaction
	- [ ] Remove transaction validation in activity sheet
	- [ ] Remove parsing/mapping of transaction data
- [ ] Update api to change new xls downloads
	- [ ] Remove transaction from downloaded sheet
	
> [!NOTE]
> Note to QA: Affected modules: Download template, download xls and import xls (basic activity sheet)
