### ISSUE TITLE
Review data completeness alert for activity result element

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1542]
_**User story:** As a user, I want to know when I have completed the basic mandatory information for an activity `result` element, so that I know when I can publish data without errors. If I see an element "not completed" alert, I want it to be clear what information is missing so that I can correct it._

**Data completeness according to the IATI Standard:**
For the [result element](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/),
- the attribute @/type is mandatory to populate.
- the following sub-elements are mandatory: [title](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/title/) and [indicator](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/)
- the following sub-elements are optional: [description](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/description/), [document-link](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/document-link), [reference](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/reference/)

-------
**User issues:**
1) The data completeness alert for `result` shows as not completed even when I have populated the basic mandatory fields following the logic above (I have tested this in a test activity [here](https://iatipublisher-staging.yipl.com.np/activity/925/result/355/edit)):

![image](https://github.com/user-attachments/assets/f467544c-979d-4c4c-acb0-bf370d64d090)

2) It is not clear when entering the result what is a mandatory vs. optional field, the same as fixed in this issue [#1501](https://github.com/younginnovations/iatipublisher/issues/1501). In particular, the user does not know that adding an indicator is mandatory
![image](https://github.com/user-attachments/assets/0e5a5d5e-0286-493e-8a07-cb015cec08e4)

## Tasks
- [x] Make changes for form level
- [x] Make changes for xml import
- [x] Make changes for xls import (result, indicator, period)
- [x] Test above

**Comment by emmajclegg** [comment]
One comment I'll make on this task @praweshsth & @PG-Momik is that this user need to see which data fields are mandatory vs. optional on IATI Publisher's data entry screens will apply across the entire tool, and improvements will massively help make the tool more intuitive to users. I'm not saying we need to fix this all at once, but I hope it's useful to keep the bigger picture in mind.

The fix you've applied in #1501 works for that `document-link` element, but if another idea looks better in this `result` case then please suggest it. We can also create some space to get direct user feedback on different design ideas if useful.

The data completeness alert part of this task is related, but feel free to split into a separate GitHub issue if it makes sense to work on the two separately.

Happy to discuss if needed.

**Comment by PG-Momik** [comment]
@emmajclegg I've looked into it.

> 1. The data completeness alert for result shows as not completed even when I have populated the basic mandatory fields following the ...

This is because, result is only considered complete if indicator and period are complete as well.  In the example you've given, indicator is not completely filled. 
I've looked into the standard and as you've mentioned, only @type, title and indicator are mandatory. Even inside indicator only [title](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/title/) and [description](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/description/) are mandatory (per my interpretation). 
But the standard is not strictly implemented in publisher right now.

**For this we can change the logic to determine result completeness by:**
   - **EITHER** disregard period completeness check **OR** only check for period completion if period exist.
   - **EITHER** disregard indicator completeness check **OR** only check for indicator completeness if indicator exists.
   - Change logic for indicator completeness check, to only take the 'title' element into account. (Basically other sub elements are taken into consideration when calculating indicator completeness)

> 2. It is not clear when entering the result what is a mandatory vs. optional field, the same as fixed in ...

Besides collapsing optional fields in the form like in issue [1501](https://github.com/younginnovations/iatipublisher/issues/1501), we could add some visual queues in result detail page and indicator detail page. Example (open to suggestion):

![Group 41](https://github.com/user-attachments/assets/518ee494-d873-451b-b879-bee84d97a2b9)

![Group 40](https://github.com/user-attachments/assets/6ca7d9c4-a4f7-4c66-89e7-ed873cf85574)

**Comment by emmajclegg** [comment]
Thanks @PG-Momik. This is a document that helps visualise the mandatory vs. optional elements of results, indicators and periods: [IATI Results Overview](https://docs.google.com/document/d/1fNVRu6OZqGNLbTt8WJV9QX0DUFO6ZqanftStT9b-EXs/edit#heading=h.440v5ppy374p) (I appreciate it's a very confusing area of the Standard, even for us)

> Even inside indicator only [title](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/title/) and [description](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/description/) are mandatory (per my interpretation).

Inside `indicator`, [title](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/title/) and @/measure are mandatory. [description](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/description/) and the other attributes are optional.

> This is because, result is only considered complete if indicator and period are complete as well.

A `result` must have an associated `indicator`, that's correct. But an `indicator` does not need to have a `period`.

I think it's important we match the mandatory logic of the Standard exactly. So yes, IATI Publisher should check that a result has an indicator.

For the interface - yes, the changes you've suggested look like they would help. I do think showing a lot of optional fields as "missing" in the interface is confusing to users (below's just an example):

![image](https://github.com/user-attachments/assets/24350422-fbed-4a29-a7c0-42df4d212885)

On these kinds of overview screens, is there a better way to show "missing" only next to fields that are mandatory? I think the optional fields don't need to appear here unless the user has populated them.

**Comment by PG-Momik** [comment]
@emmajclegg 
> Inside indicator, [title](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/title/) and @/measure are mandatory. [description](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/result/indicator/description/) and the other attributes are optional.

I will implement this.

>  I think the optional fields don't need to appear here unless the user has populated them.

This can be done but will take up a lot of time because: 
Detail pages are rendered from the frontend. Unlike form builder that has information if an element/attribute is mandatory or not, frontend  doesnt not have this sort of information. Which is why each element/attribute is checked if filled or not and the 'Missing' label is rendered when displaying any detail page. This means changes made to how 'Missing' label is displayed needs to be everywhere (each detail page + each component, to maintain consistency).

I'll work on the I commented earlier. Changes for 'Missing' label can be worked on later on a different issue.

**Comment by PG-Momik** [comment]
@emmajclegg  As I work on this, I've come up with some questions: 
1. Since `Result` completion now depends upon only : `@type`, `title`, `indicator > measure` and `indicator > title`, every other subelement will now be considered optional. This brings up the question that should all other optional fields be collapsed ?
2. If yes, then this brings the question how should the sub elements be collapsed? Example : For `Result > Document link`, it already has some subelements collapsed. If we were to collapse `document-link` since its an optional element, we could collapse the document-link sub element. Do we still need to collapse sub elements within  Result > document-link ?
3. Since we are no longer taking `Period` into account to check if `Result` is complete or not, this would mean every subelement in `Period` is optional. Does this mean all subelements in period will be collapsed by default?

Changes we make based on these questions will later be implemented for other activity elements as well.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik 

> I'll work on the changes I commented earlier. Changes for 'Missing' label can be worked on later on a different issue.

That's fine. An easier option here would be to review the language (which we're planning to do anyway as part of translation work). If "missing" were replaced with a blank space "" for example, there is not the same implication to the user that the value needs populating. I'll create a new GitHub issue to log it.

> 1. Since Result completion now depends upon only : @type, title, indicator > measure and indicator > title, every other subelement will now be considered optional. This brings up the question that should all other optional fields be collapsed ?
> 2. If yes, then this brings the question how should the sub elements be collapsed? Example : For Result > Document link, it already has some subelements collapsed. If we were to collapse document-link since its an optional element, we could collapse the document-link sub element. Do we still need to collapse sub elements within Result > document-link ?
> 3. Since we are no longer taking Period into account to check if Result is complete or not, this would mean every subelement in Period is optional. Does this mean all subelements in period will be collapsed by default?

Let's discuss tomorrow and I can take these questions away to my team if need be. The original user need here was to see what's mandatory vs. optional because a) we get queries from people where they (and us) can't figure out why their results section is "not completed", and b) we often get people publishing data with a mandatory field missing, which causes an error. 

Looking at AidStream for inspiration, your simplified UI presents mandatory vs. optional very well:

![image](https://github.com/user-attachments/assets/ddc919a4-5751-4282-871f-d71a20649176)

**Comment by emmajclegg** [comment]
I hope we clarified the data completeness part of this issue earlier today:
- where a user has started populating the `result` element, IATI Publisher should check that mandatory fields (and an `indicator`) have been added. If the user has not touched the `result` element, IATI Publisher should not check anything about it as `result` is not a "core" field to publish.
- where a user has started populating a `period`, IATI Publisher should check that mandatory fields are complete. if `period` has not been started, IATI publisher should not check for it.
- A "completed" label is not necessary for the `result` element, as it doesn't make sense in this context
- A "not completed" label, however, is useful to flag if a mandatory element is missing. Otherwise - the user will publish data and have various validation errors to troubleshoot.

Any questions let me know.

I suggest we separate the data entry form design out into a separate issue as I'm not convinced that collapsing optional fields across the whole tool is the best approach to take.

**Comment by PG-Momik** [comment]
Thanks @emmajclegg for the summary. I've made the changes listed above. 
One last question I have regarding this is whether or not we'll be showing "double tick"

![Image](https://github.com/user-attachments/assets/923c720c-a7e6-4ef7-9d9f-63566c5b0193)

**Comment by subash-cm** [comment]
@PG-Momik 
- [ ] 1. For multiple results, one with complete field and another without mandatory field, 'not completed' alert is not displayed. And, double tick on sidebar is still displayed
- [ ] 2. Upon adding/editing 'period-end ' in indicator, 500 server error is displayed. The value is saved, but 'not completed' alert should not be displayed after filling up mandatory fields in "period"

**Comment by subash-cm** [comment]
@PG-Momik 

- [ ] In multiple results, when one has indicator and other doesn't have any, "not completed" alert is not displayed

![image](https://github.com/user-attachments/assets/fad9a7ba-f5cb-45f9-aa00-0f0b73f29680)

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik. The data completeness alert looks to be working as expected at the `result` sub-element level.

How are `indicator` sub-elements checked for completeness currently? For example, in my [test activity indicator here](https://iatipublisher-staging.yipl.com.np/result/504/indicator/919/edit), I've managed to save: 
- a reference `code` without `vocabulary` 
- a baseline `date` without `year`
- a document-link `format` without `url`, `title` and `category`

I notice the result "not completed" label isn't triggered in the above scenario, but even if it was, it wouldn't be clear to the user where the missing data is. I suggest we think about this as a separate issue as some point, particularly as it relates to improving the usability of [data entry forms](https://github.com/younginnovations/iatipublisher/issues/1553), which I discussed with Bibha and Prawesh yesterday.

> We could write a script to refresh completeness status for all existing activities. Do let me know if this is necessary.

This would be ideal, for the benefit of users' existing data. How long roughly would this take to write, and could it be repurposed to other IATI elements that we review the data completeness of in future?

**Comment by PG-Momik** [comment]
@emmajclegg We could not recreate 'not complete' NOT being triggered by just filling:
-  a reference code without vocabulary
-  a baseline date without year
-   a document-link format without url, title and category

We looked into the indicator you've linked . The indicator has ` @measure` and `title` filled properly, which makes indicator complete. This in-turn makes result complete as well.

For indicator we check.
1. Check if `@measure` is filled. If not, it flags indicator incomplete. If filled, continue to next step.
2. Check if `title` narrative and language is filled. If not, it flags indicator incomplete. If filled, continue to next step.
3. Check  if `period` is filled. If not, it flags indicator as **COMPLETE**. If filled, continue to next step.
4. Check if `period start` and `period end` date is filled. If filled. Result is complete. Else not.

**Comment by emmajclegg** [comment]
> @emmajclegg We could not recreate 'not complete' NOT being triggered by just filling:
> 
> - a reference code without vocabulary
> - a baseline date without year
> - a document-link format without url, title and category
> We looked into the indicator you've linked . The indicator has  @measure and title filled properly, which makes indicator complete. This in-turn makes result complete as well.


Ok, understood @PG-Momik. For reference, the above scenario will cause the user to have critical validation errors in their indicator data, as there are mandatory fields of optional sub-elements missing. But I suggest we take this forward with the [data entry form](https://github.com/younginnovations/iatipublisher/issues/1553) work as mentioned, as the nested structure is too complicated to wrap into the result completeness alert.

> It took under 2 hrs to write the script. The script will refresh all element completion status. It can be used in the future as well if conditions for calculating completion is change.

Ok, that sounds reasonable and definitely worth doing in that case. 

If there's anything further you would like me to check on this issue, please let me know.
