### ISSUE TITLE
Review remaining element-level data completeness alerts for correctness

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1597]
Following implementation of #1553, can we review data-completeness logic for remaining elements where I suspect it is incorrect.

**Requirement:** 
- Elements should be marked "completed" on the Activity Data or Organisation Data pages if all their mandatory sub-elements have been populated.
- If an element has no mandatory sub-elements (e.g. `location`), then it should be marked completed if any of the optional sub-elements have been completed.

---

# Todo: 
**Activity elements:**
- [x] recipient-country and recipient-region covered in [#1595](https://github.com/younginnovations/iatipublisher/issues/1595)
- [x] contact-info
- [x] planned-disbursement

**Organisation elements:**
- [x] total-budget
- [x] recipient-region-budget
- [x] recipient-country-budget
- [x] total-expenditure
- [x] document-link

**Comment by PG-Momik** [comment]
@emmajclegg 
Following our discussion, I've reviewed the module for completeness calculation. For us to implement new completion rules that reflect the recent changes of #1553 , the actual changes in the back-end would be 1 liner. However we'd need to update some of the existing unit tests and also perform some degree of manual testing. 

cc: @BibhaT

**Comment by emmajclegg** [comment]
> For us to implement new completion rules that reflect the recent changes of https://github.com/younginnovations/iatipublisher/issues/1553 , the actual changes in the back-end would be 1 liner. However we'd need to update some of the existing unit tests and also perform some degree of manual testing.

Ok thanks @PG-Momik. This sounds sensible to do in that case.

In terms of new work to pick up when you can this month, I've ordered the "proposed user story/task" Github list in rough order of priority, so this issue doesn't need to be done straight away. #1596, for example, is at the top as it's causing users to publish data with errors, so that issue would be higher impact to work on.

**Comment by PG-Momik** [comment]
@emmajclegg
As mentioned in the meeting today, here are the list of elements and queries concerning them:

1. Conditions
    - In IATI Publisher, Conditions is considered complete when:
    - Attached = false
    - OR Attached = true + required fields of the optional condition subelement

2. Contact info
    - Should the completeness logic for contact info be the same as the recent changes made for location element(where location would be complete if the reference attribute is filled or any of the optional subelement is filled)
    - OR should contact info be considered complete if the type attribute is filled + any one of the optional sub element is filled.

3. Planned disbursement
    - Currently planned disbursement is considered to complete when all its required fields + planned_end is filled.
    - Should planned end be changed from optional to required
    - OR should the planned end not affect complete status.

cc: @BibhaT

**Comment by emmajclegg** [comment]
Thanks for flagging these @PG-Momik - they do seem like edge cases.

**1. Conditions**
> - In IATI Publisher, Conditions is considered complete when:
> - Attached = false
> - OR Attached = true + required fields of the optional condition subelement

This makes sense^^. According to the IATI schema, it looks fine to just enter "Attached = true" without the `condition` sub-element. But for data interpretation, I think it's expected that the `condition` sub-element be populated in this scenario.

**2. Contact info**
Similar to conditions, the IATI schema won't return an error if only the `type` attribute is populated, but this doesn't make much sense from an interpretation perspective. I recommend we do this:

> OR should contact info be considered complete if the type attribute is filled + any one of the optional sub element is filled.

**3. Planned disbursement**
Having, checked the [schema](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd#L2063) again, `period-end` is definitely an optional field. This does make sense as planned disbursements can be for a single specific date, rather than covering a period.

Therefore - the period-end date should not affect the completion status.

4. (Organisation Data) - Recipient Region Budget

Relatedly, I noticed that the recipient-region sub-element in this data entry form is marked "optional" when it should be mandatory. Can we change that to make sure the data completeness logic is correct here?

![image](https://github.com/user-attachments/assets/98659496-3ba7-4361-82c8-bfafab734b37)

Any questions, let me know.

**Comment by PG-Momik** [comment]
@emmajclegg 

> Relatedly, I noticed that the recipient-region sub-element in this data entry fo....

Recipient region has been changed to a non-optional subelement. However, none of the fields within this sub-element are mandatory in the current implementation; they are also optional in the schema ([Recipient region in schema](
https://github.com/IATI/IATI-Schemas/blob/53552b2f0d51e050f11cf19caa7cc684956fc0cb/iati-organisations-schema.xsd#L390))

This does not impact the current changes, as the recipient region budget will be complete if the required fields within all the non-optional sub-elements are populated. Nonetheless, I wanted to flag this in case it needs to be addressed differently.

cc: @BibhaT @Sanam-07

**Comment by PG-Momik** [comment]
@Sanam-07 The testables for this are:

Elements should be complete when required fields in the non-optional subelement are filled. This applies for form level as well as all the imports.

**Comment by emmajclegg** [comment]
For info - this newly raised issue related to recipient-country completeness (#1634) may make sense to look at in the context of this issue.

**Comment by Sanam-07** [comment]
:  [ ] Issue 1 : Check the completeness of the activity while importing from the XML File.

Pre-condition : 

1. The user should be logged-In. 
2. The XML should contain all the activity element filled. 
3. The XML file should not contain already existing activity.

Steps to reproduce : 
1. Click on the add activity button.
2. Click on the Import Activities by XML/CSV.
3. Upload the XML File and import activity.

Expected Result : The activity should be successfully imported and all the element in the activity should be filled.
Actual Result : The activity is successfully imported but the sector and transaction element is marked as incomplete.
![image](https://github.com/user-attachments/assets/d4010a71-34c8-4bf2-975b-5af822ec6bae)

- [ ]  Issue 2 : Check the completeness of the activity while importing from the CSV File.

Pre-condition : 

1. The user should be logged-In. 
2. The CSV should contain all the activity element filled. 
3. The CSV file should not contain already existing activity.

Steps to reproduce : 
1. Click on the add activity button.
2. Click on the Import Activities by XML/CSV.
3. Upload the CSV File and import activity.

Expected Result : The activity should be successfully imported and all the element in the activity should be filled.
Actual Result : The activity is successfully imported but the result and transaction element is marked as incomplete.
![image](https://github.com/user-attachments/assets/a0891211-f6d0-4912-bd08-ce2595a7b4ed)

**Comment by PG-Momik** [comment]
Hi @emmajclegg, I have some questions regarding this issue epecially on these 2 elements:
1. Contact info
2.

**Comment by emmajclegg** [comment]
@PG-Momik - I agree yes to both of those questions.

> ...since 2 percentage fields cannot be 100%.

I'm not sure I understand this ^^ but form validation for sector, similar to what there is for recipient country / region likely makes sense.

**Comment by PG-Momik** [comment]
@emmajclegg Regarding tag
1. In the publisher, tag -> vocabulary is not a required field for completion . It does not have red *.
![Image](https://github.com/user-attachments/assets/70ac7750-72d7-4dae-a072-8a4cf0f7037f)


2. IATI validator throws a critical error when validating an xml that doesnt have 'vocabulary' attribute in the tag element
![Image](https://github.com/user-attachments/assets/d96d64ae-618e-482e-b055-2ace0b5efedd)

3. The IATI standard states that vocabulary is a required field. 

![Image](https://github.com/user-attachments/assets/61b23c22-45cb-4d91-bacb-7f1e6789dd57)

Therefore we've currently changed tag vocabulary to be a required field for completion. Do let us know if the change mentioned above do not seem correct. 

cc: @Sanam-07 @BibhaT

**Comment by emmajclegg** [comment]
Hi @PG-Momik - yes, good spot. I agree vocabulary should be a required field for the `tag` element.

**Comment by Sanam-07** [comment]
Hi @emmajclegg,

### Update on the Issue:
Requirement Summary:

1. Completeness Criteria: An element is considered complete when all mandatory fields (marked with a red *) are filled.
2. Optional Sub-elements: Mandatory fields within optional sub-elements do not affect the parent element's completeness, except for specific cases (e.g., location, RR, RC, contact info).

**Current Progress:**

I’m currently testing both form inputs and imports for create and update scenarios. This task is quite time-intensive, with approximately effort of 30 hours spent. The testing process involves:

1. Importing datasets element by element. (elements besides result, transaction , planned-disbursement, budget have been covered for form and XML level)
2. Confirming element completeness. (elements besides result, transaction , planned-disbursement, budget have been covered for form and XML level)
3. Changing data and re-importing. 
4. Reconfirming completeness.

**Comment by PG-Momik** [comment]
@emma This has been deployed to staging. But changes made in issue #1567 are not present yet. Will redeploy again with those changes tomorrow.

**Comment by emmajclegg** [comment]
Thanks @PG-Momik. 

I've run through the different element data entry forms. Only thing I've noticed:

**Organisation data:** `recipient-region-budget`

"Status" is marked mandatory when it should be optional [according to the schema](https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-organisations-schema.xsd#L507). This is affecting the data completeness logic and is inconsistent with logic in `recipient-country-budget` currently.

![Image](https://github.com/user-attachments/assets/ff5aa801-9067-493f-aaec-93208d56967b)

**Comment by Sanam-07** [comment]
Hi @emmajclegg 

I noticed that the "Recipient Region" section is marked as mandatory; however, none of its attributes (vocabulary, code, narrative, or language) are required fields. This seems inconsistent, as the red astrik (*)  implies that the sub-element is mandatory, however none of its attributes are mandatory.
![Image](https://github.com/user-attachments/assets/4f02ea11-9e3c-4587-a643-5c74665d8860)
Additionally, according to the IATI Standard, at least one recipient region must be provided. 
![Image](https://github.com/user-attachments/assets/4c368d19-8f09-4b6f-bd2e-bd5a674600de)
While this does not affect the completeness calculation currently, could you confirm if the implementation is fine (recipient-region-budget could be complete even if RR is empty)
Looking forward to your clarification.

**Comment by emmajclegg** [comment]
Hi @Sanam-07 

> I noticed that the "Recipient Region" section is marked as mandatory; however, none of its attributes (vocabulary, code, narrative, or language) are required fields. This seems inconsistent, as the red astrik (*) implies that the sub-element is mandatory, however none of its attributes are mandatory.

I agree - it's correct that `recipient-region` (the sub-element) is mandatory, but all of the fields within it are optional. I assume this is to retain flexibility in the IATI Standard about which field(s) a user populates within `recipient-region` - i.e. either 'code' or 'narrative'.

For IATI Publisher, the main thing is that `recipient-region` should have a red asterisk (*) in the data entry form, which is already the case.

> While this does not affect the completeness calculation currently, could you confirm if the implementation is fine (recipient-region-budget could be complete even if RR is empty)

Ideally, IATI Publisher would be checking that something has been populated within `recipient-region`, rather than nothing. But, if this is complicated, I suggest leaving it as is for now. `recipient-region-budget` is not a commonly used field by our user base.

Thanks - any questions let me know

**Comment by PG-Momik** [comment]
>  I suggest leaving the data completeness logic as is for now.

Lets leave it as is.

**Comment by emmajclegg** [comment]
ok, thanks all - all looks good.

**Comment by PG-Momik** [comment]
Thanks @emmajclegg.  This will be deployed on Monday.
