### ISSUE TITLE
Transaction List - change date display and add column sorting

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1607]
The activity Transaction List currently lists 10 transactions per page:
![image](https://github.com/user-attachments/assets/80128174-76ee-4fd2-9186-fc4d19e58b1a)
 
User issues:
- Transaction dates are not displayed in full so it is hard for users to differentiate transactions in the same month
- It is unclear how transactions are ordered in the table so it can be hard to find the one you're looking for

Being able to easily manage more than 10 transactions in the interface will be important as we start to migrate publishers with more data and make bulk import of transactions easier to do.

## TODO

- [x] display transaction date in full, to match how users see it in the data entry form (yyyy-mm-dd)
- [x] show transactions ordered by type, then by date in the table? This is to match how people are used to seeing them displayed in other IATI tools, like d-portal
- [ ] (ideally) give users the ability to sort the columns in the table. This is so that they can manage large volumes of transactions easier in the interface.

**Comment by PG-Momik** [comment]
@emmajclegg 

### Show transactions ordered by type

We're trying to implement ordering transactions by type, followed by transaction date. However, this approach raises a "bug" because transaction types are stored in the database as numeric values (1 to 5) rather than descriptive strings (e.g., "Incoming Funds," "Expenditure," etc.):

![Image](https://github.com/user-attachments/assets/ce285f68-69b4-4ac7-934e-4abca79b890d)

 
As a result, the ordering appears as follows:
(Note how "Interest Payment" and "Incoming Funds" are not grouped together in the table.)

![Image](https://github.com/user-attachments/assets/c9586fb2-096c-43cb-93b2-a4e1a0911487)


We recommend only ordering by transaction date (in descending order) and omitting ordering by transaction type to avoid confusion for users.

---

### Display transaction date in full, to match how users see it in the data entry form (yyyy-mm-dd)

In the screenshot above, the date format has been updated to dd/mm/yyyy, which aligns with the format used in the data entry form. This is different from the suggested format yyyy-mm-dd. Could you confirm if this format is acceptable? Format's can be changed to other variation like : (Nov 19, 2024, 19 Nov, 2024, mm/dd/yyyyy, etc)

---

### (Ideally) give users the ability to order the columns in the table

Should users have the ability to sort or rearrange columns in the table? We are uncertain about the practical benefits this feature would provide. If this feature is to be implemented, does the system need to remember user preferences (e.g., column order) across sessions? This change is not a minor change unlike the 2 stated above. 

Do let us know if we understood this wrong.


cc: @BibhaT @Yash-ftW @Sanam-07

**Comment by Sanam-07** [comment]
- [ ] Issue 1 : All of the Transaction Date should display in (yyyy-mm-dd) format.
![image](https://github.com/user-attachments/assets/6f0e69a2-f267-4841-9932-546628927bed)

**Comment by emmajclegg** [comment]
Hi @PG-Momik 

> We're trying to implement ordering transactions by type, followed by transaction date. However, this approach raises a "bug" because transaction types are stored in the database as numeric values (1 to 5) rather than descriptive strings (e.g., "Incoming Funds," "Expenditure," etc.):

Ordering by the numerical transaction type code is what I meant, sorry for not being clear. If you look at other IATI tools, like this [d-portal example](https://d-portal.org/savi/?aid=GB-EDU-133903-301134), transactions are grouped and ordered by the type code (so "incoming funds" are listed first for example). For consistency across tools, I think it's fine to copy that ordering.

If we don't allow users to order the columns in the Transaction List, it's even more important that same type transactions are grouped together so that users can find the ones they're looking for.

> In the screenshot above, the date format has been updated to dd/mm/yyyy, which aligns with the format used in the data entry form. This is different from the suggested format yyyy-mm-dd. Could you confirm if this format is acceptable? Format's can be changed to other variation like : (Nov 19, 2024, 19 Nov, 2024, mm/dd/yyyyy, etc)

"yyyy-mm-dd" date format would be preferred, to match d-portal, and because it's less ambiguous (I know dd/mm/yyyy would be misinterpreted in North America). I see "yyyy-mm-dd" in the data entry forms, so I assume that can vary based on computer settings.

![Image](https://github.com/user-attachments/assets/f44e068a-30a3-453b-b6fe-6c11b3384693)

> Should users have the ability to sort or rearrange columns in the table? We are uncertain about the practical benefits this feature would provide. If this feature is to be implemented, does the system need to remember user preferences (e.g., column order) across sessions? This change is not a minor change unlike the other 2.

If we implement the two changes above then no, this change is not essential. I suggested it as another way to help users find specific transactions, but we can leave this change for now.

**Comment by emmajclegg** [comment]
Summarising my understanding from today's call,
- Allowing users to sort the transaction table columns themselves (i.e. by ascending or descending value) would be straightforward to implement(?) Apologies for any misunderstanding on the ask.
- It is possible to add filters on transaction type, in a similar style to the activity ones:
![Image](https://github.com/user-attachments/assets/32f699d3-b61e-49d4-b21e-100679c369b6)

Both of these ^^ are nice to haves and would help users better work with the transaction table. If they are not complicated to implement, then they are worthwhile doing.

@BibhaT - reflecting on your question about ordering - if we implement the changes above, then the default order that IATI Publisher displays transactions in becomes less important. So, as you were saying, it does seem reasonable to display the most recently created (or edited) transactions at the top of the table. It was only if users are unable to sort the table themselves that I'd insist on the default ordering by type and date.

**Comment by PG-Momik** [comment]
@emmajclegg  This has been deployed to staging.

**Comment by emmajclegg** [comment]
Great - the transaction list sorting and display dates look good.

For the transaction type filters, it looks like all possible types are displayed (which is a lot to display on screen), even if the publisher only uses a few transaction types in their data. Could we display only the transaction types that the publisher has used instead?

![Image](https://github.com/user-attachments/assets/5714b210-0bb5-413e-a68f-db3f7e26bb57)


If that is not straightforward, an alternative could be to display filters for the most common transaction types ("Incoming Funds", "Outgoing Commitment", "Disbursement", "Expenditure") and group the other, less frequently used, types into an "Other" category.

This would simplify the interface as many of the "other" transaction types are unlikely to be used by our user base.

A nice-to-have with either solution would be to also display number of transactions of each type within the filter icons, similar to the activity list example:

![Image](https://github.com/user-attachments/assets/b637faf2-6d47-46be-a90e-805c067af1be)

**Comment by Yash-ftW** [comment]
@emmajclegg , This has been deployed to staging.

**Comment by emmajclegg** [comment]
This looks great, thanks. Happy for the changes to be deployed.

**Comment by Yash-ftW** [comment]
Hi @emmajclegg , The fix has been deployed to staging.
