### ISSUE TITLE
Activity Element Complete Status

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#221]
Get the status (complete or incomplete) of each element of the activity and show it on the activity detail page

**TASKS**

- [x] Categorize the elements based on their sub-elements and attributes
- [x] Develop a generic function to check the mandatory fields of each element
- [x] Check for each mandatory element and attributes in the data
- [x] Return true or false based on complete status
- [x] Show in activity detail page

**Comment by man-git007** [comment]
Complete status for basis elements done and merged to main. Close manually
