### ISSUE TITLE
Implement Landing page UI

### ISSUE THREAD

**Issue by titungdup** [younginnovations/iatipublisher#23]
The landing page UI with necessary folders, files and routes. The UI reference is in this [link](https://www.figma.com/file/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=409%3A2096)

**TASKS**

- [x] Route implementation
- [x] View (blade file), controller setup
- [x] Setup layout in view folder
- [x] Develop html file.
- [x] Removal of bootstrap
