### ISSUE TITLE
activity-detail-UI

### ISSUE THREAD

**Issue by Man0zZ** [younginnovations/iatipublisher#262]
- [x] elements details UI
- [x] header dropdown font size
- [x] spacing fix
- [x] #214 issue 8 >> what is activity tooltip display wrong information
- [x] #214 issue 9 >> default-finance-type does not match with the design
- [x] #214 issue 10 >> Padding between narrative and @xml lang

**Comment by man-git007** [comment]
@Man0zZ If done. please close the issue
