### ISSUE TITLE
User Module

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#31]
**TASKS**

- [ ] User and Organization table migration and seed
- [ ] Services and repositories for user
- [ ] User Listing page 
- [ ] Unit test cases
