### ISSUE TITLE
Activity Complex Element Complete Status

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#313]
Get the status (complete or incomplete) of the complex element of the activity and show it on the activity detail page

**TASKS**

- [x] Categorize the result element based on their sub-elements and attributes
- [x] Return true or false based on complete status
- [x] Show in activity detail page
- [x] Maintain complete status in DB
- [x] Write tests for complete status

**NOTE**
Need to run `php artisan migrate:fresh --seed`

**Comment by man-git007** [comment]
This has been merged to `main` branch and manually closed
