### ISSUE TITLE
Organization Publish

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#346]
**Tasks**

- [x] Conversion of data to XML file
- [x] Upload XML file to S3 server
- [x] Publish organization to IATI Registry

**Comment by man-git007** [comment]
@sriza What is the status of this issue? Also, which branch is related to this issue? Please mention the branch and if merged to the `main` branch lets close this issue.

cc @SauravSilwal10

**Comment by sriza** [comment]
@man-git007 The branch related to this issue has already been merged to the main branch.
