### ISSUE TITLE
Manage routes

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#408]
manage routes for activity, result, indicator, and period elements.

**TASKS**

- [x] rename `activities` to `activity`
- [x] manage RedirectActivity middleware
- [x] manage results, indicators and period routes
- [x] Mange route in php and vue
- [x] Sub-group middleware for transactions, result, indicator and period
- [x] Refactor code

cc @sriza @Sanilblank

**Comment by man-git007** [comment]
Merged to main branch and closed manually
