### ISSUE TITLE
Landing page with sign in

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#7]
As a user, I want to view the landing page so that I can learn about the tool, sign up and Sign in

Content and structure - [check the link](https://docs.google.com/document/d/16G0tjT1iprHO2jIp3cn9cyFC1HGnt8FUl5zWXaoWldo/edit#heading=h.xhjhjaeyq7rz)

**Acceptance Criteria:**
_Sign in_
- [ ] Username is required if the field is empty
- [ ] Password is required if the field is empty
- [ ] The credentials are not correct, if the password is incorrect
- [ ] username doesn't exist, if username is doesn't match
- [ ] After successful sign up, take user to activities listing page. 
- [ ] Show user to complete the publishing settings and default values untill they complete them.

_Join in_
- [ ] Show link to 'Join in' into the system and when clicked show the options (Registered in IATI and Not registered in IATI) to join in and replace the 'Join in' link with 'Sign in'
- [ ] After signing up, show sections of settings that need to be taken care of before adding and publishing activities and organisation and keep showing until those settings are taken care of. 

Design Link: https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?node-id=1305%3A16112&scaling=min-zoom&page-id=409%3A2096&starting-point-node-id=1226%3A10734

**Linked Issues**
#23 #30 #31 #43 #112

**Comment by praweshsth** [comment]
1. Reset password link doesn't work
2. When the credentials don't match, highlight the password field box too.

**Comment by man-git007** [comment]
@praweshsth Can we close this issue?
