### ISSUE TITLE
Activity reporting org form

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#719]
**Tasks**

- [x] Reporting org form create and update
- [x] complete status
- [x] Replace reporting org in xml data
- [x] UI ( Detail page, routes, forms)

**Comment by sriza** [comment]
Completed and merged to main branch
