### ISSUE TITLE
New User Registration in IATI Publisher and IATI Registry

### ISSUE THREAD

**Issue by sriza** [younginnovations/iatipublisher#743]
**Tasks**

- [ ] New user form
- [ ] User and publisher creation in IATI and publisher

**Comment by shreyaydi** [comment]
Here is the design for the screens of the sign up flow for users that have not registered in the IATI Registry. You can navigate through the screens using "<-"  "->" keys on the keypad or click anywhere on the screen,

[Figma Link](https://www.figma.com/proto/upgUy5i65LYC3iiqYVnACW/IATI-Publisher-Platform?page-id=3147%3A46778&node-id=11222%3A187178&viewport=639%2C-797%2C0.14&scaling=min-zoom&starting-point-node-id=11222%3A187178)

@k8hughes @DaveEade49 @praweshsth @sriza @man-git007 @rajkarnikar11

**Comment by SauravSilwal10** [comment]
@sriza Issue Found in this branch 

- [ ] Issue 1: Doesn't validate the name and ID that has already register on IATI registry.


https://user-images.githubusercontent.com/78422663/202432934-120f84c4-a467-4e44-bcba-c4baf36d8725.mp4


- [ ] Issue 2: Tick mark should be given instead of number


![Image](https://user-images.githubusercontent.com/78422663/202433095-80361e2e-ad0d-4573-900c-9a7769ee3dee.png)


- [ ] Issue 3: Why contact email should be unique?



![Image](https://user-images.githubusercontent.com/78422663/202433270-8fa01ee3-c0f1-4251-999a-e74500e193c0.png)



![Image](https://user-images.githubusercontent.com/78422663/202433520-93f583a2-bccb-4150-b33e-bc21830baab5.png)


- [ ] Issue 4: Verification email doesn't appear on user mailbox.


- [ ] Issue 5: Tick mark should be dynamic.


https://user-images.githubusercontent.com/78422663/202435684-40eb2898-7cba-4cd9-9067-0aedecd116ce.mp4



- [ ] Issue 6: Validation error is not displayed on edit form

### Steps 

- At first enter an invalid email and enter valid email 


- [ ] Issue 7: Source tool tip is not clickable  

![Image](https://user-images.githubusercontent.com/78422663/202434124-51db5225-6029-4bcc-8874-9b9702302dc4.png)


- [ ] Issue 8: No validation for Publisher Logo Url


https://user-images.githubusercontent.com/78422663/202435412-0c782e68-ce44-42f3-b662-aa91eb31f005.mp4

**Comment by k8hughes** [comment]
Looking at the figma designs we are happy to approve these.

**Comment by praweshsth** [comment]
Thank you @k8hughes

**Comment by praweshsth** [comment]
@k8hughes @DaveEade49 we are also implementing to show if the publisher has been activated in IATI Registry or not. Do we restrict the user to publish organisation and activity data if the publisher has not been activated in IATI Registry?

**Comment by k8hughes** [comment]
Yes I think we have to

**Comment by DaveEade49** [comment]
@praweshsth - quick question - current process is that when a new publisher registers on Registry - an email comes to support to validate they are ok, and they get approved via registry - is this still the process even though the source for registration is different?

**Comment by praweshsth** [comment]
Thank you @k8hughes
@DaveEade49 Yes. This only provides a platform for users to register publisher and create account in IATI Registy. After registration, the activation process is same as before. IATI has to verify the publisher manually in IATI Registry.
