### ISSUE TITLE
Element delete

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#751]
Enable element delete feature

**TASKS**

- [x] Add delete button in every element section
- [x] Delete element functionality

**Comment by SauravSilwal10** [comment]
@man-git007 

- [ ] **Issue 1 : Whenever user delete the title element , our system gets freeze.**


https://user-images.githubusercontent.com/78422663/202652099-37bf9570-39dd-4c54-b1df-55763dbee0aa.mp4



- [ ] **Issue 2 : Delete button is  missing on Transaction and Result Element.**


- [ ] **Issue 3 : Whenever user delete the certain element ,page should reload to top of activity detail page , so that user can read the toast message.**



https://user-images.githubusercontent.com/78422663/202651705-597b8d79-468e-41e7-9abd-09f7ffc29e8e.mp4


- [ ] **Issue 4  : Issue with transaction element** 

### Steps 

1. fill transaction element and save it 

Actual Result 
-  Doesn't display on transaction detail page.



https://user-images.githubusercontent.com/78422663/202653098-a205757b-e77e-4317-9317-272a37f9edb9.mp4

**Comment by man-git007** [comment]
@titungdup Can you look into Issue 2 and 3.

**Comment by man-git007** [comment]
@SauravSilwal10 Create a new issue for Issue no. 4 and assign to @Sanilblank

**Comment by man-git007** [comment]
Merged to main branch and closed manually
