### ISSUE TITLE
Language file update

### ISSUE THREAD

**Issue by Man0zZ** [younginnovations/iatipublisher#77]
**Tasks**

- [ ]  Translation of landing, signup, settings and reset page.
- [x] Creation of laravel lang files.
- [x] Line height for help text

**Comment by man-git007** [comment]
@Man0zZ What is the status of this issue and which branch is related to this issue?

**Comment by Man0zZ** [comment]
@man-git007 This issue is yet to be fixed. It is related to 77-auth-translation branch

**Comment by man-git007** [comment]
@Man0zZ OK. We will use this branch during our translation feature

cc @sriza @Sanilblank @jenishshrestha @SauravSilwal10

**Comment by PG-Momik** [comment]
Closing this because issues and tasks associated to language are handled in #885
