### ISSUE TITLE
Activities download in CSV and XML

### ISSUE THREAD

**Issue by Sanilblank** [younginnovations/iatipublisher#774]
TASKS

- [ ] Users should be able to select the activities they want to download from the activities listing page
- [ ] Upon selection and clicking of the download button activities should be downloaded in CSV or XML format as required
- [ ] The downloaded file should be uploadable to the IATI publisher

DISCUSSIONS
- Users should also be able to download a single activity (No difference when downloading single or multiple activities)
- When downloading activity in XML format, if the core elements are not filled, the downloaded file will cause issues when performing IATI schema validation during upload so we may need to complete the validation when the user wants to download in XML format to prevent problems during the upload (May need discussion)
- The above problem will not arise when downloading in CSV format as we only check the headers and the entire validation process is present in the system itself

LIMITATIONS IN CSV
- The system has no provision for uploading narratives in multiple languages (and some other sub-elements) while uploading CSV and hence, a similar limitation will be present while downloading CSV i.e. if there are multiple data that cannot be uploaded via CSV, only the first one of such data will be downloaded
- If the current CSV upload format is used for download, users will not be able to download results, indicators, and periods
- Also, when uploading a CSV file, we assume everything to be in the default defined language but while downloading CSV, if the language for a defined narrative or such is different from the default defined language, it may cause problems as to how to show the actual language

cc. @praweshsth @man-git007

**Comment by praweshsth** [comment]
@k8hughes @DaveEade49 Please give us your feedback on this.

**Comment by DaveEade49** [comment]
Folks, here are my comments - I've added numbers to the points so they can be cross-referenced....

**Tasks:**
3. The downloaded file should be in the same format as the the template that can be downloaded as blank - if data items are missing from the download, this should stop population of these fields when the .csv is in edit mode before save and upload.
**Discussions.** 
2. The only reason I can see that someone would want to download xml and then upload was if they wanted to make changes, this then gives us two options: 1. We validate the upload xml and call out any missing core items, or we download stubs for the core items so that they are more easily editable and can be entered by the user. We'd still need to validate the upload anyway, but surely we would do that at the point of publishing, rather than at the point of upload?
**Limitations**
1. This is file - we need to call it out in the user manual - we may need to think about having a separate page of help for upload as it's a bit niche.
2. May need more info on this - why are these values not in the upload template?
3. Not sure I understand why you would assume that - what are the implications of having multiple languages in the upload? Surely the upload is just a neat way of avoiding manual keying into the system.

**Comment by praweshsth** [comment]
> Folks, here are my comments - I've added numbers to the points so they can be cross-referenced....
> 
> **Tasks:** 3. The downloaded file should be in the same format as the the template that can be downloaded as blank - if data items are missing from the download, this should stop population of these fields when the .csv is in edit mode before save and upload. **Discussions.** 2. The only reason I can see that someone would want to download xml and then upload was if they wanted to make changes, this then gives us two options: 1. We validate the upload xml and call out any missing core items, or we download stubs for the core items so that they are more easily editable and can be entered by the user. We'd still need to validate the upload anyway, but surely we would do that at the point of publishing, rather than at the point of upload? **Limitations**
> 
> 1. This is file - we need to call it out in the user manual - we may need to think about having a separate page of help for upload as it's a bit niche.
> 2. May need more info on this - why are these values not in the upload template?
> 3. Not sure I understand why you would assume that - what are the implications of having multiple languages in the upload? Surely the upload is just a neat way of avoiding manual keying into the system.

Tasks:
3. It is not possible to restrict user to not populate the CSV file as you have mentioned. It is different from the IATI Publisher system. 
Discussions:
2. During uploading of XML, there is a schema validation which checks if the required elements and required fields as per the IATI standard are available or not. If all or some are not available, the system will show error messages with details and the file is not uploaded. Similarly, when someone downloads the xml, we will do the validation and show the errors if any required elements or required fields are missing and tell them that they have to resolve these issues before uploading otherwise they will not be able to upload it later. 
Limitations:
1. For this we will put information in download and upload section. And while downloading the CSV, the file will contain the default language and default currency for narrative and currency for now. If the narrative and currency are in different language and currency, they will be not be included in the CSV
2. This was decided before we started working on upload CSV. As it will be a long number of columns if we include Result in it. 
3. As mentioned in no. 1

**Comment by SauravSilwal10** [comment]
@Sanilblank Issue found in this branch.

- [ ] Issue 1: When a user tries to download the CSV, nothing has happened.


https://user-images.githubusercontent.com/78422663/209065894-5a1af5bc-b198-4344-8ea2-c7f07c0b43df.mp4

- [ ] Issue 2: When none of the activities is selected but the XML file has been downloaded.

https://user-images.githubusercontent.com/78422663/209067064-44ed35bb-baf7-4601-a370-5bd2b642f557.mp4
