### ISSUE TITLE
Unit Test signup and login

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#91]
Write unit test for publisher signup and login

**TASKS**
- [ ] Unit test login module
- [ ] Enable dummy db for testing
- [ ] Enable user factory
- [ ] Unit test register
