### ISSUE TITLE
System version UI

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#967]
Build UI to show the system version. The system version includes PHP and JS packages used with their versions and upgradable version as well.

**TASKS**
- [x] Build a bash file to read composer and package JSON files
- [x] List out PHP dependencies with the current version and available version in tabular format
- [x] List out Node dependencies with the current version and available version in tabular format
- [x] Only the super admin can access this route and UI

**Comment by man-git007** [comment]
@Sanilblank Guide @PG-Momik with this.
