### ISSUE TITLE
UI for elementjsonschema.json

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#968]
Develop UI to edit elementjsonschema.json file of organization and element. 

**TASKS**

- [ ] Develop UI for editing json file.
- [ ] Edit only hover text, help text, label etc.
- [ ] Access only to superadmin
- [ ] Might need to save json data in DB for that need to write necessary migration file

NOTE: use `vue3-json-editor` as node package and use `json-editor` branch as a reference or can be developed using this branch
