### ISSUE TITLE
Create persistent storage for laravel logs

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#970]
Setup persistent storage in the production server for storing laravel logs

**TASKS**

- [x] Create a storage of 100MB volume
- [x] Symlink the `storage/logs` to persistent storage
- [x] Copy to `storage/logs` after each deployment

**Comment by man-git007** [comment]
@pravin-yipl Let's finish this today

cc @praweshsth
