### ISSUE TITLE
Remove unnecessary node packages

### ISSUE THREAD

**Issue by man-git007** [younginnovations/iatipublisher#999]
Uninstall unnecessary node packages

**TASKS**
- [x] List out node packages to be un-installed
- [x] Uninstall packages and commit the package.json and lock file.
- [x] Update the packages if any

**Comment by titungdup** [comment]
Removed unsued package: 
- stylelint-config-rational-order
- stylelint-order
